// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ConfigTheme.
const (
	Dark  ConfigTheme = "dark"
	Light ConfigTheme = "light"
)

// Valid indicates whether the value is a known member of the ConfigTheme enum.
func (e ConfigTheme) Valid() bool {
	switch e {
	case Dark:
		return true
	case Light:
		return true
	default:
		return false
	}
}

// Defines values for FolderNodeKind.
const (
	Folder FolderNodeKind = "folder"
)

// Valid indicates whether the value is a known member of the FolderNodeKind enum.
func (e FolderNodeKind) Valid() bool {
	switch e {
	case Folder:
		return true
	default:
		return false
	}
}

// Defines values for MigrationStatusState.
const (
	Ok            MigrationStatusState = "ok"
	Rebuilding    MigrationStatusState = "rebuilding"
	RolledBack    MigrationStatusState = "rolled_back"
	Unrecoverable MigrationStatusState = "unrecoverable"
)

// Valid indicates whether the value is a known member of the MigrationStatusState enum.
func (e MigrationStatusState) Valid() bool {
	switch e {
	case Ok:
		return true
	case Rebuilding:
		return true
	case RolledBack:
		return true
	case Unrecoverable:
		return true
	default:
		return false
	}
}

// Defines values for NoteNodeKind.
const (
	NoteNodeKindNote NoteNodeKind = "note"
)

// Valid indicates whether the value is a known member of the NoteNodeKind enum.
func (e NoteNodeKind) Valid() bool {
	switch e {
	case NoteNodeKindNote:
		return true
	default:
		return false
	}
}

// Defines values for ReindexRequestMode.
const (
	Full        ReindexRequestMode = "full"
	Incremental ReindexRequestMode = "incremental"
)

// Valid indicates whether the value is a known member of the ReindexRequestMode enum.
func (e ReindexRequestMode) Valid() bool {
	switch e {
	case Full:
		return true
	case Incremental:
		return true
	default:
		return false
	}
}

// Defines values for StaleWriteErrorCode.
const (
	StaleWrite StaleWriteErrorCode = "stale_write"
)

// Valid indicates whether the value is a known member of the StaleWriteErrorCode enum.
func (e StaleWriteErrorCode) Valid() bool {
	switch e {
	case StaleWrite:
		return true
	default:
		return false
	}
}

// Defines values for WSEnvelopeEvent.
const (
	WSEnvelopeEventFolderCreated   WSEnvelopeEvent = "folder:created"
	WSEnvelopeEventFolderDeleted   WSEnvelopeEvent = "folder:deleted"
	WSEnvelopeEventFolderMoved     WSEnvelopeEvent = "folder:moved"
	WSEnvelopeEventMigrationStatus WSEnvelopeEvent = "migration:status"
	WSEnvelopeEventNoteCreated     WSEnvelopeEvent = "note:created"
	WSEnvelopeEventNoteDeleted     WSEnvelopeEvent = "note:deleted"
	WSEnvelopeEventNoteMoved       WSEnvelopeEvent = "note:moved"
	WSEnvelopeEventNoteUpdated     WSEnvelopeEvent = "note:updated"
	WSEnvelopeEventReindexComplete WSEnvelopeEvent = "reindex:complete"
	WSEnvelopeEventReindexStarted  WSEnvelopeEvent = "reindex:started"
	WSEnvelopeEventSessionAssigned WSEnvelopeEvent = "session:assigned"
	WSEnvelopeEventTagsUpdated     WSEnvelopeEvent = "tags:updated"
)

// Valid indicates whether the value is a known member of the WSEnvelopeEvent enum.
func (e WSEnvelopeEvent) Valid() bool {
	switch e {
	case WSEnvelopeEventFolderCreated:
		return true
	case WSEnvelopeEventFolderDeleted:
		return true
	case WSEnvelopeEventFolderMoved:
		return true
	case WSEnvelopeEventMigrationStatus:
		return true
	case WSEnvelopeEventNoteCreated:
		return true
	case WSEnvelopeEventNoteDeleted:
		return true
	case WSEnvelopeEventNoteMoved:
		return true
	case WSEnvelopeEventNoteUpdated:
		return true
	case WSEnvelopeEventReindexComplete:
		return true
	case WSEnvelopeEventReindexStarted:
		return true
	case WSEnvelopeEventSessionAssigned:
		return true
	case WSEnvelopeEventTagsUpdated:
		return true
	default:
		return false
	}
}

// Config defines model for Config.
type Config struct {
	AppName    string `json:"appName"`
	DailyNotes struct {
		Folder   string `json:"folder"`
		Template string `json:"template"`
	} `json:"dailyNotes"`
	Editor struct {
		FontSize   int     `json:"fontSize"`
		LineHeight float32 `json:"lineHeight"`
		VimMode    bool    `json:"vimMode"`
	} `json:"editor"`
	Theme ConfigTheme `json:"theme"`
}

// ConfigTheme defines model for Config.Theme.
type ConfigTheme string

// CreateFolderRequest defines model for CreateFolderRequest.
type CreateFolderRequest struct {
	// Name New folder basename (single path segment, no `/`).
	Name string `json:"name"`

	// ParentPath Canonical relative path under notes/ to the parent folder, or ""
	// for the vault root.
	ParentPath string `json:"parent_path"`
}

// CreateNoteRequest defines model for CreateNoteRequest.
type CreateNoteRequest struct {
	// ParentPath Canonical relative path under notes/ to the parent folder, or ""
	// for the vault root. NFC + lowercase per DATA-11; the server
	// re-canonicalizes defensively.
	ParentPath string `json:"parent_path"`

	// Title Note title (basename without `.md`); the server appends `.md`.
	Title string `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FolderNode defines model for FolderNode.
type FolderNode struct {
	// Children ONLY populated when this FolderNode appears inside a Tree response.
	// Empty (or omitted) when used as a standalone response (POST /folders,
	// POST /folders/move).
	Children *[]TreeNode `json:"children,omitempty"`

	// Kind Discriminator value identifying this node as a folder.
	Kind FolderNodeKind `json:"kind"`

	// Name Basename (last path segment).
	Name string `json:"name"`

	// Path Canonical relative path under notes/ (NFC + lowercase per DATA-11)
	Path string `json:"path"`
}

// FolderNodeKind Discriminator value identifying this node as a folder.
type FolderNodeKind string

// MigrationStatus defines model for MigrationStatus.
type MigrationStatus struct {
	// FailedMigration Filename of the migration that triggered Path 1 (only set when state=rolled_back)
	FailedMigration *string `json:"failed_migration,omitempty"`

	// LogsPath Absolute path to the structured log file (only set when state in {rolled_back, unrecoverable})
	LogsPath *string `json:"logs_path,omitempty"`

	// NotesIndexed Count of rows currently in the `notes` table (informational)
	NotesIndexed *int `json:"notes_indexed,omitempty"`

	// State Current migration runner state. Surfaces the three-path resilience
	// model from DESIGN.md §4.4.
	//   - "ok"            — schema is current; no action required
	//   - "rolled_back"   — Path 1 fired; previous schema active; banner shown (UX-03)
	//   - "rebuilding"    — Path 2 in progress; UI shows ReindexProgress overlay
	//   - "unrecoverable" — Path 3 fired; static error page is served and the SPA cannot reach this endpoint (documented for future use)
	State MigrationStatusState `json:"state"`
}

// MigrationStatusState Current migration runner state. Surfaces the three-path resilience
// model from DESIGN.md §4.4.
//   - "ok"            — schema is current; no action required
//   - "rolled_back"   — Path 1 fired; previous schema active; banner shown (UX-03)
//   - "rebuilding"    — Path 2 in progress; UI shows ReindexProgress overlay
//   - "unrecoverable" — Path 3 fired; static error page is served and the SPA cannot reach this endpoint (documented for future use)
type MigrationStatusState string

// MoveFolderRequest defines model for MoveFolderRequest.
type MoveFolderRequest struct {
	// NewPath New canonical relative path under notes/ for the folder.
	NewPath string `json:"new_path"`

	// OldPath Current canonical relative path under notes/ for the folder.
	OldPath string `json:"old_path"`
}

// MoveNoteRequest defines model for MoveNoteRequest.
type MoveNoteRequest struct {
	// NewPath New canonical relative path under notes/ (with `.md` extension).
	NewPath string `json:"new_path"`
}

// Note defines model for Note.
type Note struct {
	// Content Raw markdown content of the note
	Content string             `json:"content"`
	Id      openapi_types.UUID `json:"id"`

	// Path Canonicalized relative path under notes/ (NFC + lowercase per DATA-11)
	Path string `json:"path"`

	// UpdatedAt Wall-clock UTC time of the last successful write
	UpdatedAt time.Time `json:"updated_at"`
}

// NoteList defines model for NoteList.
type NoteList struct {
	Notes []NoteSummary `json:"notes"`
}

// NoteNode defines model for NoteNode.
type NoteNode struct {
	Id openapi_types.UUID `json:"id"`

	// Kind Discriminator value identifying this node as a note.
	Kind NoteNodeKind `json:"kind"`

	// Path Canonical relative path under notes/ (NFC + lowercase per DATA-11)
	Path string `json:"path"`

	// Title First-H1 title or filename without `.md`; never empty.
	Title string `json:"title"`

	// UpdatedAt Wall-clock UTC of last filesystem mtime observed by the indexer.
	UpdatedAt time.Time `json:"updated_at"`
}

// NoteNodeKind Discriminator value identifying this node as a note.
type NoteNodeKind string

// NoteSummary defines model for NoteSummary.
type NoteSummary struct {
	Id openapi_types.UUID `json:"id"`

	// Path Canonical relative path under notes/ (NFC + lowercase per DATA-11)
	Path string `json:"path"`

	// Title First-H1 title or filename without `.md`; never empty
	Title string `json:"title"`

	// UpdatedAt Wall-clock UTC of last filesystem mtime observed by the indexer
	UpdatedAt time.Time `json:"updated_at"`
}

// ReindexRequest defines model for ReindexRequest.
type ReindexRequest struct {
	// Mode "full"        — Path 2: drop derived tables, re-run all migrations on the new (clean) schema, walk every .md file
	// "incremental" — re-run the cheap mtime-based delta scan only (DATA-09)
	Mode *ReindexRequestMode `json:"mode,omitempty"`
}

// ReindexRequestMode "full"        — Path 2: drop derived tables, re-run all migrations on the new (clean) schema, walk every .md file
// "incremental" — re-run the cheap mtime-based delta scan only (DATA-09)
type ReindexRequestMode string

// ReindexResponse defines model for ReindexResponse.
type ReindexResponse struct {
	// NotesIndexed Count of rows in the `notes` table after the reindex completed (Phase 2 only — Phase 4 streams this via WS)
	NotesIndexed *int `json:"notes_indexed,omitempty"`

	// StartedAt Wall-clock UTC when the reindex began (Phase 2 returns AFTER it finishes; this is still the start time)
	StartedAt time.Time `json:"started_at"`
}

// StaleWriteError Returned by PUT /notes/{id} when If-Match does not match the
// current file's updated_at (SYNC-06). The client surfaces
// SYNC-05's Save-anyway / Discard banner using
// current_updated_at as the new comparator.
type StaleWriteError struct {
	Code             StaleWriteErrorCode `json:"code"`
	CurrentUpdatedAt time.Time           `json:"current_updated_at"`
	Message          string              `json:"message"`
}

// StaleWriteErrorCode defines model for StaleWriteError.Code.
type StaleWriteErrorCode string

// Tree defines model for Tree.
type Tree struct {
	// Root Top-level (root) entries — children of the vault root (notes/). The
	// ROOT itself is implicit; folders nest via children[].
	Root []TreeNode `json:"root"`
}

// TreeNode defines model for TreeNode.
type TreeNode struct {
	union json.RawMessage
}

// UpdateNoteRequest defines model for UpdateNoteRequest.
type UpdateNoteRequest struct {
	// Content New raw markdown content; replaces the entire file
	Content string `json:"content"`
}

// UpdateNoteResponse defines model for UpdateNoteResponse.
type UpdateNoteResponse struct {
	Id        openapi_types.UUID `json:"id"`
	Path      string             `json:"path"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// WSEnvelope WebSocket event envelope (DESIGN.md §5.2). The `event` enum is
// locked verbatim and mirrors the Go const block in
// backend/internal/wshub/envelope.go and the TS dispatch table
// in frontend/src/lib/useSessionSync.ts.
type WSEnvelope struct {
	Event WSEnvelopeEvent `json:"event"`

	// OriginSessionId UUID of the session that originated the mutation. Empty
	// string for server-originated events (reindex:*,
	// migration:status). Clients ignore events whose
	// origin_session_id matches their own (SYNC-03 origin
	// filter).
	OriginSessionId string `json:"origin_session_id"`

	// Payload Event-specific payload; shape determined by `event`.
	Payload interface{} `json:"payload"`
}

// WSEnvelopeEvent defines model for WSEnvelope.Event.
type WSEnvelopeEvent string

// WSFolderCreatedPayload defines model for WSFolderCreatedPayload.
type WSFolderCreatedPayload struct {
	Name string `json:"name"`
	Path string `json:"path"`
}

// WSFolderDeletedPayload defines model for WSFolderDeletedPayload.
type WSFolderDeletedPayload struct {
	Path      string `json:"path"`
	Recursive bool   `json:"recursive"`
}

// WSFolderMovedPayload defines model for WSFolderMovedPayload.
type WSFolderMovedPayload struct {
	NewPath string `json:"new_path"`
	OldPath string `json:"old_path"`
}

// WSNoteCreatedPayload defines model for WSNoteCreatedPayload.
type WSNoteCreatedPayload struct {
	Id        openapi_types.UUID `json:"id"`
	Path      string             `json:"path"`
	Title     string             `json:"title"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// WSNoteDeletedPayload defines model for WSNoteDeletedPayload.
type WSNoteDeletedPayload struct {
	Id   openapi_types.UUID `json:"id"`
	Path string             `json:"path"`
}

// WSNoteMovedPayload defines model for WSNoteMovedPayload.
type WSNoteMovedPayload struct {
	Id        openapi_types.UUID `json:"id"`
	NewPath   string             `json:"new_path"`
	OldPath   string             `json:"old_path"`
	Title     string             `json:"title"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// WSNoteUpdatedPayload defines model for WSNoteUpdatedPayload.
type WSNoteUpdatedPayload struct {
	Id        openapi_types.UUID `json:"id"`
	Path      string             `json:"path"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// WSReindexCompletePayload defines model for WSReindexCompletePayload.
type WSReindexCompletePayload struct {
	NotesIndexed int `json:"notes_indexed"`
}

// WSReindexStartedPayload Empty payload — server-originated.
type WSReindexStartedPayload = map[string]interface{}

// NoteId defines model for NoteId.
type NoteId = openapi_types.UUID

// DeleteFolderParams defines parameters for DeleteFolder.
type DeleteFolderParams struct {
	// Path Canonical relative path under notes/ (NFC + lowercase per DATA-11)
	Path string `form:"path" json:"path"`

	// Recursive When false (default), the server returns 409 folder_not_empty if the
	// folder has any children. The Phase 3 Delete-folder dialog (UI-SPEC
	// §Surface 4) always sets recursive=true after the user confirms the
	// content-count copy.
	Recursive *bool `form:"recursive,omitempty" json:"recursive,omitempty"`
}

// PutNoteByIdParams defines parameters for PutNoteById.
type PutNoteByIdParams struct {
	// IfMatch Optimistic concurrency comparator (SYNC-06). When present,
	// the server compares this value against the file's current
	// updated_at (RFC3339Nano UTC). On mismatch the server
	// returns 409 with `code: stale_write` and
	// `current_updated_at` in the body — the client surfaces
	// SYNC-05's Save-anyway / Discard banner. Permissive when
	// absent (curl / automation friendly). Server treats the
	// value as an opaque string round-trip; max length 256 chars.
	IfMatch *string `json:"If-Match,omitempty"`
}

// GetApiV1WsParams defines parameters for GetApiV1Ws.
type GetApiV1WsParams struct {
	// SessionId Per-tab UUID generated by the client (sessionStorage).
	// Server adopts this as the connection's session_id; the
	// handshake message echoes it for confirmation. Treated as
	// opaque; max length 128 chars enforced in middleware
	// (T-04-03).
	SessionId *openapi_types.UUID `form:"session_id,omitempty" json:"session_id,omitempty"`
}

// PostAdminReindexJSONRequestBody defines body for PostAdminReindex for application/json ContentType.
type PostAdminReindexJSONRequestBody = ReindexRequest

// PutConfigJSONRequestBody defines body for PutConfig for application/json ContentType.
type PutConfigJSONRequestBody = Config

// PostFoldersJSONRequestBody defines body for PostFolders for application/json ContentType.
type PostFoldersJSONRequestBody = CreateFolderRequest

// PostFolderMoveJSONRequestBody defines body for PostFolderMove for application/json ContentType.
type PostFolderMoveJSONRequestBody = MoveFolderRequest

// PostNotesJSONRequestBody defines body for PostNotes for application/json ContentType.
type PostNotesJSONRequestBody = CreateNoteRequest

// PutNoteByIdJSONRequestBody defines body for PutNoteById for application/json ContentType.
type PutNoteByIdJSONRequestBody = UpdateNoteRequest

// PostNoteMoveJSONRequestBody defines body for PostNoteMove for application/json ContentType.
type PostNoteMoveJSONRequestBody = MoveNoteRequest

// AsFolderNode returns the union data inside the TreeNode as a FolderNode
func (t TreeNode) AsFolderNode() (FolderNode, error) {
	var body FolderNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFolderNode overwrites any union data inside the TreeNode as the provided FolderNode
func (t *TreeNode) FromFolderNode(v FolderNode) error {
	v.Kind = "folder"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFolderNode performs a merge with any union data inside the TreeNode, using the provided FolderNode
func (t *TreeNode) MergeFolderNode(v FolderNode) error {
	v.Kind = "folder"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNoteNode returns the union data inside the TreeNode as a NoteNode
func (t TreeNode) AsNoteNode() (NoteNode, error) {
	var body NoteNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoteNode overwrites any union data inside the TreeNode as the provided NoteNode
func (t *TreeNode) FromNoteNode(v NoteNode) error {
	v.Kind = "note"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNoteNode performs a merge with any union data inside the TreeNode, using the provided NoteNode
func (t *TreeNode) MergeNoteNode(v NoteNode) error {
	v.Kind = "note"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TreeNode) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t TreeNode) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "folder":
		return t.AsFolderNode()
	case "note":
		return t.AsNoteNode()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t TreeNode) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TreeNode) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Trigger a full or incremental re-index
	// (POST /admin/reindex)
	PostAdminReindex(w http.ResponseWriter, r *http.Request)
	// Report the migration runner state
	// (GET /admin/status)
	GetAdminStatus(w http.ResponseWriter, r *http.Request)
	// Read user configuration
	// (GET /config)
	GetConfig(w http.ResponseWriter, r *http.Request)
	// Replace user configuration (whole-document)
	// (PUT /config)
	PutConfig(w http.ResponseWriter, r *http.Request)
	// Delete a folder (TREE-06) — non-empty requires recursive=true
	// (DELETE /folders)
	DeleteFolder(w http.ResponseWriter, r *http.Request, params DeleteFolderParams)
	// Create a folder (TREE-04)
	// (POST /folders)
	PostFolders(w http.ResponseWriter, r *http.Request)
	// Rename or move a folder (TREE-05, TREE-07)
	// (POST /folders/move)
	PostFolderMove(w http.ResponseWriter, r *http.Request)
	// List all indexed notes (metadata only)
	// (GET /notes)
	GetNotes(w http.ResponseWriter, r *http.Request)
	// Create a new note (TREE-03)
	// (POST /notes)
	PostNotes(w http.ResponseWriter, r *http.Request)
	// Delete a note by UUID (TREE-06)
	// (DELETE /notes/{id})
	DeleteNoteById(w http.ResponseWriter, r *http.Request, id NoteId)
	// Read a note by UUID
	// (GET /notes/{id})
	GetNoteById(w http.ResponseWriter, r *http.Request, id NoteId)
	// Replace the content of a note by UUID
	// (PUT /notes/{id})
	PutNoteById(w http.ResponseWriter, r *http.Request, id NoteId, params PutNoteByIdParams)
	// Rename or move a note (TREE-05, TREE-07)
	// (POST /notes/{id}/move)
	PostNoteMove(w http.ResponseWriter, r *http.Request, id NoteId)
	// Return the full folder/file hierarchy under notes/ (TREE-01)
	// (GET /tree)
	GetTree(w http.ResponseWriter, r *http.Request)
	// WebSocket endpoint (HTTP/1.1 Upgrade)
	// (GET /ws)
	GetApiV1Ws(w http.ResponseWriter, r *http.Request, params GetApiV1WsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Trigger a full or incremental re-index
// (POST /admin/reindex)
func (_ Unimplemented) PostAdminReindex(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Report the migration runner state
// (GET /admin/status)
func (_ Unimplemented) GetAdminStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read user configuration
// (GET /config)
func (_ Unimplemented) GetConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Replace user configuration (whole-document)
// (PUT /config)
func (_ Unimplemented) PutConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a folder (TREE-06) — non-empty requires recursive=true
// (DELETE /folders)
func (_ Unimplemented) DeleteFolder(w http.ResponseWriter, r *http.Request, params DeleteFolderParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a folder (TREE-04)
// (POST /folders)
func (_ Unimplemented) PostFolders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rename or move a folder (TREE-05, TREE-07)
// (POST /folders/move)
func (_ Unimplemented) PostFolderMove(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all indexed notes (metadata only)
// (GET /notes)
func (_ Unimplemented) GetNotes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new note (TREE-03)
// (POST /notes)
func (_ Unimplemented) PostNotes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a note by UUID (TREE-06)
// (DELETE /notes/{id})
func (_ Unimplemented) DeleteNoteById(w http.ResponseWriter, r *http.Request, id NoteId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read a note by UUID
// (GET /notes/{id})
func (_ Unimplemented) GetNoteById(w http.ResponseWriter, r *http.Request, id NoteId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Replace the content of a note by UUID
// (PUT /notes/{id})
func (_ Unimplemented) PutNoteById(w http.ResponseWriter, r *http.Request, id NoteId, params PutNoteByIdParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rename or move a note (TREE-05, TREE-07)
// (POST /notes/{id}/move)
func (_ Unimplemented) PostNoteMove(w http.ResponseWriter, r *http.Request, id NoteId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return the full folder/file hierarchy under notes/ (TREE-01)
// (GET /tree)
func (_ Unimplemented) GetTree(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// WebSocket endpoint (HTTP/1.1 Upgrade)
// (GET /ws)
func (_ Unimplemented) GetApiV1Ws(w http.ResponseWriter, r *http.Request, params GetApiV1WsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAdminReindex operation middleware
func (siw *ServerInterfaceWrapper) PostAdminReindex(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminReindex(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAdminStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConfig operation middleware
func (siw *ServerInterfaceWrapper) GetConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutConfig operation middleware
func (siw *ServerInterfaceWrapper) PutConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFolder operation middleware
func (siw *ServerInterfaceWrapper) DeleteFolder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteFolderParams

	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "recursive" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "recursive", r.URL.Query(), &params.Recursive, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "recursive"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recursive", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFolder(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostFolders operation middleware
func (siw *ServerInterfaceWrapper) PostFolders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostFolders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostFolderMove operation middleware
func (siw *ServerInterfaceWrapper) PostFolderMove(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostFolderMove(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNotes operation middleware
func (siw *ServerInterfaceWrapper) GetNotes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNotes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostNotes operation middleware
func (siw *ServerInterfaceWrapper) PostNotes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostNotes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNoteById operation middleware
func (siw *ServerInterfaceWrapper) DeleteNoteById(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id NoteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNoteById(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNoteById operation middleware
func (siw *ServerInterfaceWrapper) GetNoteById(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id NoteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNoteById(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutNoteById operation middleware
func (siw *ServerInterfaceWrapper) PutNoteById(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id NoteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PutNoteByIdParams

	headers := r.Header

	// ------------- Optional header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = &IfMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutNoteById(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostNoteMove operation middleware
func (siw *ServerInterfaceWrapper) PostNoteMove(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id NoteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostNoteMove(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTree operation middleware
func (siw *ServerInterfaceWrapper) GetTree(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTree(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1Ws operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Ws(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1WsParams

	// ------------- Optional query parameter "session_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "session_id", r.URL.Query(), &params.SessionId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "session_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1Ws(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/reindex", wrapper.PostAdminReindex)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/status", wrapper.GetAdminStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/config", wrapper.GetConfig)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/config", wrapper.PutConfig)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/folders", wrapper.DeleteFolder)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/folders", wrapper.PostFolders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/folders/move", wrapper.PostFolderMove)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/notes", wrapper.GetNotes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/notes", wrapper.PostNotes)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/notes/{id}", wrapper.DeleteNoteById)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/notes/{id}", wrapper.GetNoteById)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/notes/{id}", wrapper.PutNoteById)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/notes/{id}/move", wrapper.PostNoteMove)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tree", wrapper.GetTree)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ws", wrapper.GetApiV1Ws)
	})

	return r
}

type PostAdminReindexRequestObject struct {
	Body *PostAdminReindexJSONRequestBody
}

type PostAdminReindexResponseObject interface {
	VisitPostAdminReindexResponse(w http.ResponseWriter) error
}

type PostAdminReindex202JSONResponse ReindexResponse

func (response PostAdminReindex202JSONResponse) VisitPostAdminReindexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type PostAdminReindex409JSONResponse Error

func (response PostAdminReindex409JSONResponse) VisitPostAdminReindexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PostAdminReindex503JSONResponse Error

func (response PostAdminReindex503JSONResponse) VisitPostAdminReindexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminStatusRequestObject struct {
}

type GetAdminStatusResponseObject interface {
	VisitGetAdminStatusResponse(w http.ResponseWriter) error
}

type GetAdminStatus200JSONResponse MigrationStatus

func (response GetAdminStatus200JSONResponse) VisitGetAdminStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetConfigRequestObject struct {
}

type GetConfigResponseObject interface {
	VisitGetConfigResponse(w http.ResponseWriter) error
}

type GetConfig200JSONResponse Config

func (response GetConfig200JSONResponse) VisitGetConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutConfigRequestObject struct {
	Body *PutConfigJSONRequestBody
}

type PutConfigResponseObject interface {
	VisitPutConfigResponse(w http.ResponseWriter) error
}

type PutConfig200JSONResponse Config

func (response PutConfig200JSONResponse) VisitPutConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutConfig400JSONResponse Error

func (response PutConfig400JSONResponse) VisitPutConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutConfig500JSONResponse Error

func (response PutConfig500JSONResponse) VisitPutConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFolderRequestObject struct {
	Params DeleteFolderParams
}

type DeleteFolderResponseObject interface {
	VisitDeleteFolderResponse(w http.ResponseWriter) error
}

type DeleteFolder204Response struct {
}

func (response DeleteFolder204Response) VisitDeleteFolderResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteFolder400JSONResponse Error

func (response DeleteFolder400JSONResponse) VisitDeleteFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFolder404JSONResponse Error

func (response DeleteFolder404JSONResponse) VisitDeleteFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFolder409JSONResponse Error

func (response DeleteFolder409JSONResponse) VisitDeleteFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFolder500JSONResponse Error

func (response DeleteFolder500JSONResponse) VisitDeleteFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostFoldersRequestObject struct {
	Body *PostFoldersJSONRequestBody
}

type PostFoldersResponseObject interface {
	VisitPostFoldersResponse(w http.ResponseWriter) error
}

type PostFolders201JSONResponse FolderNode

func (response PostFolders201JSONResponse) VisitPostFoldersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostFolders400JSONResponse Error

func (response PostFolders400JSONResponse) VisitPostFoldersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostFolders409JSONResponse Error

func (response PostFolders409JSONResponse) VisitPostFoldersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PostFolderMoveRequestObject struct {
	Body *PostFolderMoveJSONRequestBody
}

type PostFolderMoveResponseObject interface {
	VisitPostFolderMoveResponse(w http.ResponseWriter) error
}

type PostFolderMove200JSONResponse FolderNode

func (response PostFolderMove200JSONResponse) VisitPostFolderMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostFolderMove400JSONResponse Error

func (response PostFolderMove400JSONResponse) VisitPostFolderMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostFolderMove404JSONResponse Error

func (response PostFolderMove404JSONResponse) VisitPostFolderMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PostFolderMove409JSONResponse Error

func (response PostFolderMove409JSONResponse) VisitPostFolderMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PostFolderMove500JSONResponse Error

func (response PostFolderMove500JSONResponse) VisitPostFolderMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetNotesRequestObject struct {
}

type GetNotesResponseObject interface {
	VisitGetNotesResponse(w http.ResponseWriter) error
}

type GetNotes200JSONResponse NoteList

func (response GetNotes200JSONResponse) VisitGetNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostNotesRequestObject struct {
	Body *PostNotesJSONRequestBody
}

type PostNotesResponseObject interface {
	VisitPostNotesResponse(w http.ResponseWriter) error
}

type PostNotes201JSONResponse NoteSummary

func (response PostNotes201JSONResponse) VisitPostNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostNotes400JSONResponse Error

func (response PostNotes400JSONResponse) VisitPostNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostNotes409JSONResponse Error

func (response PostNotes409JSONResponse) VisitPostNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteNoteByIdRequestObject struct {
	Id NoteId `json:"id"`
}

type DeleteNoteByIdResponseObject interface {
	VisitDeleteNoteByIdResponse(w http.ResponseWriter) error
}

type DeleteNoteById204Response struct {
}

func (response DeleteNoteById204Response) VisitDeleteNoteByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteNoteById404JSONResponse Error

func (response DeleteNoteById404JSONResponse) VisitDeleteNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteNoteById500JSONResponse Error

func (response DeleteNoteById500JSONResponse) VisitDeleteNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetNoteByIdRequestObject struct {
	Id NoteId `json:"id"`
}

type GetNoteByIdResponseObject interface {
	VisitGetNoteByIdResponse(w http.ResponseWriter) error
}

type GetNoteById200JSONResponse Note

func (response GetNoteById200JSONResponse) VisitGetNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNoteById404JSONResponse Error

func (response GetNoteById404JSONResponse) VisitGetNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PutNoteByIdRequestObject struct {
	Id     NoteId `json:"id"`
	Params PutNoteByIdParams
	Body   *PutNoteByIdJSONRequestBody
}

type PutNoteByIdResponseObject interface {
	VisitPutNoteByIdResponse(w http.ResponseWriter) error
}

type PutNoteById200JSONResponse UpdateNoteResponse

func (response PutNoteById200JSONResponse) VisitPutNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutNoteById400JSONResponse Error

func (response PutNoteById400JSONResponse) VisitPutNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutNoteById404JSONResponse Error

func (response PutNoteById404JSONResponse) VisitPutNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PutNoteById409JSONResponse StaleWriteError

func (response PutNoteById409JSONResponse) VisitPutNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PutNoteById500JSONResponse Error

func (response PutNoteById500JSONResponse) VisitPutNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostNoteMoveRequestObject struct {
	Id   NoteId `json:"id"`
	Body *PostNoteMoveJSONRequestBody
}

type PostNoteMoveResponseObject interface {
	VisitPostNoteMoveResponse(w http.ResponseWriter) error
}

type PostNoteMove200JSONResponse NoteSummary

func (response PostNoteMove200JSONResponse) VisitPostNoteMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostNoteMove400JSONResponse Error

func (response PostNoteMove400JSONResponse) VisitPostNoteMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostNoteMove404JSONResponse Error

func (response PostNoteMove404JSONResponse) VisitPostNoteMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PostNoteMove409JSONResponse Error

func (response PostNoteMove409JSONResponse) VisitPostNoteMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PostNoteMove500JSONResponse Error

func (response PostNoteMove500JSONResponse) VisitPostNoteMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetTreeRequestObject struct {
}

type GetTreeResponseObject interface {
	VisitGetTreeResponse(w http.ResponseWriter) error
}

type GetTree200JSONResponse Tree

func (response GetTree200JSONResponse) VisitGetTreeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTree500JSONResponse Error

func (response GetTree500JSONResponse) VisitGetTreeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetApiV1WsRequestObject struct {
	Params GetApiV1WsParams
}

type GetApiV1WsResponseObject interface {
	VisitGetApiV1WsResponse(w http.ResponseWriter) error
}

type GetApiV1Ws101Response struct {
}

func (response GetApiV1Ws101Response) VisitGetApiV1WsResponse(w http.ResponseWriter) error {
	w.WriteHeader(101)
	return nil
}

type GetApiV1Ws400Response struct {
}

func (response GetApiV1Ws400Response) VisitGetApiV1WsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Trigger a full or incremental re-index
	// (POST /admin/reindex)
	PostAdminReindex(ctx context.Context, request PostAdminReindexRequestObject) (PostAdminReindexResponseObject, error)
	// Report the migration runner state
	// (GET /admin/status)
	GetAdminStatus(ctx context.Context, request GetAdminStatusRequestObject) (GetAdminStatusResponseObject, error)
	// Read user configuration
	// (GET /config)
	GetConfig(ctx context.Context, request GetConfigRequestObject) (GetConfigResponseObject, error)
	// Replace user configuration (whole-document)
	// (PUT /config)
	PutConfig(ctx context.Context, request PutConfigRequestObject) (PutConfigResponseObject, error)
	// Delete a folder (TREE-06) — non-empty requires recursive=true
	// (DELETE /folders)
	DeleteFolder(ctx context.Context, request DeleteFolderRequestObject) (DeleteFolderResponseObject, error)
	// Create a folder (TREE-04)
	// (POST /folders)
	PostFolders(ctx context.Context, request PostFoldersRequestObject) (PostFoldersResponseObject, error)
	// Rename or move a folder (TREE-05, TREE-07)
	// (POST /folders/move)
	PostFolderMove(ctx context.Context, request PostFolderMoveRequestObject) (PostFolderMoveResponseObject, error)
	// List all indexed notes (metadata only)
	// (GET /notes)
	GetNotes(ctx context.Context, request GetNotesRequestObject) (GetNotesResponseObject, error)
	// Create a new note (TREE-03)
	// (POST /notes)
	PostNotes(ctx context.Context, request PostNotesRequestObject) (PostNotesResponseObject, error)
	// Delete a note by UUID (TREE-06)
	// (DELETE /notes/{id})
	DeleteNoteById(ctx context.Context, request DeleteNoteByIdRequestObject) (DeleteNoteByIdResponseObject, error)
	// Read a note by UUID
	// (GET /notes/{id})
	GetNoteById(ctx context.Context, request GetNoteByIdRequestObject) (GetNoteByIdResponseObject, error)
	// Replace the content of a note by UUID
	// (PUT /notes/{id})
	PutNoteById(ctx context.Context, request PutNoteByIdRequestObject) (PutNoteByIdResponseObject, error)
	// Rename or move a note (TREE-05, TREE-07)
	// (POST /notes/{id}/move)
	PostNoteMove(ctx context.Context, request PostNoteMoveRequestObject) (PostNoteMoveResponseObject, error)
	// Return the full folder/file hierarchy under notes/ (TREE-01)
	// (GET /tree)
	GetTree(ctx context.Context, request GetTreeRequestObject) (GetTreeResponseObject, error)
	// WebSocket endpoint (HTTP/1.1 Upgrade)
	// (GET /ws)
	GetApiV1Ws(ctx context.Context, request GetApiV1WsRequestObject) (GetApiV1WsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostAdminReindex operation middleware
func (sh *strictHandler) PostAdminReindex(w http.ResponseWriter, r *http.Request) {
	var request PostAdminReindexRequestObject

	var body PostAdminReindexJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAdminReindex(ctx, request.(PostAdminReindexRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAdminReindex")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAdminReindexResponseObject); ok {
		if err := validResponse.VisitPostAdminReindexResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminStatus operation middleware
func (sh *strictHandler) GetAdminStatus(w http.ResponseWriter, r *http.Request) {
	var request GetAdminStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminStatus(ctx, request.(GetAdminStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminStatusResponseObject); ok {
		if err := validResponse.VisitGetAdminStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetConfig operation middleware
func (sh *strictHandler) GetConfig(w http.ResponseWriter, r *http.Request) {
	var request GetConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConfig(ctx, request.(GetConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConfigResponseObject); ok {
		if err := validResponse.VisitGetConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutConfig operation middleware
func (sh *strictHandler) PutConfig(w http.ResponseWriter, r *http.Request) {
	var request PutConfigRequestObject

	var body PutConfigJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutConfig(ctx, request.(PutConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutConfigResponseObject); ok {
		if err := validResponse.VisitPutConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteFolder operation middleware
func (sh *strictHandler) DeleteFolder(w http.ResponseWriter, r *http.Request, params DeleteFolderParams) {
	var request DeleteFolderRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteFolder(ctx, request.(DeleteFolderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteFolder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteFolderResponseObject); ok {
		if err := validResponse.VisitDeleteFolderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostFolders operation middleware
func (sh *strictHandler) PostFolders(w http.ResponseWriter, r *http.Request) {
	var request PostFoldersRequestObject

	var body PostFoldersJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostFolders(ctx, request.(PostFoldersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostFolders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostFoldersResponseObject); ok {
		if err := validResponse.VisitPostFoldersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostFolderMove operation middleware
func (sh *strictHandler) PostFolderMove(w http.ResponseWriter, r *http.Request) {
	var request PostFolderMoveRequestObject

	var body PostFolderMoveJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostFolderMove(ctx, request.(PostFolderMoveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostFolderMove")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostFolderMoveResponseObject); ok {
		if err := validResponse.VisitPostFolderMoveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNotes operation middleware
func (sh *strictHandler) GetNotes(w http.ResponseWriter, r *http.Request) {
	var request GetNotesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNotes(ctx, request.(GetNotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNotes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNotesResponseObject); ok {
		if err := validResponse.VisitGetNotesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostNotes operation middleware
func (sh *strictHandler) PostNotes(w http.ResponseWriter, r *http.Request) {
	var request PostNotesRequestObject

	var body PostNotesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostNotes(ctx, request.(PostNotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostNotes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostNotesResponseObject); ok {
		if err := validResponse.VisitPostNotesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteNoteById operation middleware
func (sh *strictHandler) DeleteNoteById(w http.ResponseWriter, r *http.Request, id NoteId) {
	var request DeleteNoteByIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteNoteById(ctx, request.(DeleteNoteByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteNoteById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteNoteByIdResponseObject); ok {
		if err := validResponse.VisitDeleteNoteByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNoteById operation middleware
func (sh *strictHandler) GetNoteById(w http.ResponseWriter, r *http.Request, id NoteId) {
	var request GetNoteByIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNoteById(ctx, request.(GetNoteByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNoteById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNoteByIdResponseObject); ok {
		if err := validResponse.VisitGetNoteByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutNoteById operation middleware
func (sh *strictHandler) PutNoteById(w http.ResponseWriter, r *http.Request, id NoteId, params PutNoteByIdParams) {
	var request PutNoteByIdRequestObject

	request.Id = id
	request.Params = params

	var body PutNoteByIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutNoteById(ctx, request.(PutNoteByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutNoteById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutNoteByIdResponseObject); ok {
		if err := validResponse.VisitPutNoteByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostNoteMove operation middleware
func (sh *strictHandler) PostNoteMove(w http.ResponseWriter, r *http.Request, id NoteId) {
	var request PostNoteMoveRequestObject

	request.Id = id

	var body PostNoteMoveJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostNoteMove(ctx, request.(PostNoteMoveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostNoteMove")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostNoteMoveResponseObject); ok {
		if err := validResponse.VisitPostNoteMoveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTree operation middleware
func (sh *strictHandler) GetTree(w http.ResponseWriter, r *http.Request) {
	var request GetTreeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTree(ctx, request.(GetTreeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTree")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTreeResponseObject); ok {
		if err := validResponse.VisitGetTreeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1Ws operation middleware
func (sh *strictHandler) GetApiV1Ws(w http.ResponseWriter, r *http.Request, params GetApiV1WsParams) {
	var request GetApiV1WsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1Ws(ctx, request.(GetApiV1WsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1Ws")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1WsResponseObject); ok {
		if err := validResponse.VisitGetApiV1WsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1H3rciO3sf+rdM3/f8pkwpsuu46lcqVkrWQr2dXqiFI2Kc/WEpxpkohmgDGAIZfeUtX5dB7g1HmHvEce",
	"JU9yCg3MheRQ0tqS1vEHl0jOAI1Go/vXN+ynIJJpJgUKo4ODT0HGFEvRoKJP59LgWWz/ilFHimeGSxEc",
	"BNfXZ69ATsDMEIQ0CK2LGdMIOzBjGvAji0yyBCkQ/vVf/wsaEXSkmIlmGYuBXuYCIhljO+gE3I6YMTML",
	"OoFgKQYHAY+DTqDwp5wrjIMDo3LsBDqaYcosMROpUmaCgyDP6UmzzOxb2igupsHt7W3xMC3iWIoJn9q/",
	"WBxzuwKWXCiZoTIcdXAwYYnGTpDVvvoUsCw7J1rs0icsT+x0f2I6QxV0gpR9fI1iambBwcv9TpByUXzc",
	"2aCmE8SMJ0vLSv2ZRExkEqNapYEG+2wSDKZZwszaelaH2Rns7m/ysr4PPxYU1QZ8X74ix3/HyNjZMOZG",
	"qs9erDBD/vMqiTsviESe5mlwsLdL63Qf/lDOy4XBKSo7ccIF/oB8OjOro/Re1oepjVLxSuTp2A0y5+kb",
	"Ga/S4Sn2z46lTJCJBu74JaxQUo3YxCszw3Uxi5m6CToBCkvhj8XHhAZ7f98OFYK7InbllhTzNVFyrJAZ",
	"PKUdvsSfctTExdVdEuWhqOuDc1yAEw0YM432IWhpLqYJgj3ZoHGaojAdEBJG/VG7Z0n6yNIssTT8vThX",
	"G3KbMYXCfCDtsDHrMRNS8IgloDBhhs/9ZLmwhFi9pPtgJGkpN5AnsgNSQRiEQSgmUtHvc8t7UFKaXihW",
	"iMuUtBzSwX2cr9PqNdl2Ntt92crkL7FqOD89ht9DIheoIqvLM1Tw6ujqqLuzc0gPa1RzVKFQ2I0KGvjP",
	"qCHGCQrN55gstzGvv32LDTdJk0hZs0K/QauUqQU3M5kbGPXSeNSukwUsy1DE2v20Kl4xaj4VXeGPwufs",
	"oiOuaRtPlHIqbnXrIq85qtmFNB8mMhdx0+JT1JpNN95wRtWuFngMA/9fl/63b//Hio/+v51710WEVRM2",
	"Lckd/XO/grV1zXgSKxSbG/X2/PXfIJNZbs1BDIsZCjAzrqEajjaHKQ1caG4/wpVCBIU6k0JjLxQnaWaW",
	"0JIKZMqNwbjtBso1xsA0MNCGiZglFlMU70Hr4u3wCvpOvHUnFCuf+6mcY9tJJDeY0jr+v8JJcBD8v34F",
	"e/oeK/QtUbT625I5TCm2tJ9vuGjAQa+4/ZRywYxUMGdJjsBjFIZPllxMHR8EccCuwRHWq+l2b0/fN4hG",
	"s6b9rlSvCdNmRbl+hlL9xXqldYeWaH/eyV+TT2JwJ7hPe77hU8UsxUPDTK43BXXCeILxh7R4bnOhpzxx",
	"LPQAtnwUzIwZMIpPp6gwhgu7/B1oSZEsQaNxIqkNM/itkomdZsyim9V1DwZ7Hwyb6p7+KWlifiKneotm",
	"PxprmeTG892rcG1UHpnc0pPIKUy4VYgNFFlE/alGVQdyoTCSc1RsnODtKpX9a00nBPs9tz99baRiU+xb",
	"+vye9RI5bVoCycIHLmL8iA2H4ljmwljmKrnQEOXKKtRkaQm0CxrR6yMwlixoceHQPIHEFSJ3dve/bgJ5",
	"tNyGad1Ete1UuRCoHHt6MMzVhEWoiQgzU4hd4rNCzROOIsJQpDLGBCZKpvDqZHj2/XkvjeGf/9jv7fdC",
	"AdCFMJA3YQC1/8jBIQUCvFztocU5LHJUeCEvBqjtEY1kB/CSNrHPHUKmcM5lrotx7UBzPIQxc+uZyYWA",
	"1vVfu4O9djkqjnOexFxMHXnlqLuW75mSU4VaH8L1Gb2v4RJpAy/8L2AFJWHLYrwV4QmDary9gkrLVh4B",
	"WjsIGZuiXT8Z4xiYiInNw4sjiJgQ0oBCFs2cQkQRZ5ILA61YRrlVXRiDhSST3Aq6VfpthyO8lpQW/9b4",
	"Rs5hsd6gs0rs/RDZCVCjdpHzewEwLrYcXwuCo4co0QJ91czBptoUuOgKB+Q3DqBM4m3g0B+Cx6NDJvEW",
	"Ota4WhLVqXi0jcd3ot9H4HCLoBNBQcCPxqJTKdq9uwxU36HEXhrfu9I7l2eX1gQLhUFhNpd0yRaQMnUT",
	"2zPtn6pHVpq2n8erePGB+PCeqMm9uID/jPHjYIMqGNTI7k6QZ7EFkx9YA8fesSTpRomMbuD66hgMryw5",
	"QSKdRxFqPckTWChOHCxXbkft2jfu3WNeAyPF5q3QtW3vX/NGmS6iPw8ConacYZ6mTC03sei6MNLI26hp",
	"BvNOgO6Vh0fBvJa+OuIloX7/vKj0oT7nKVfadH/Y8X6ntUgFVlzxPA9BoPU50XotvV8pwHLi5NZOpZfa",
	"YAqpE+qxt6bjJUm3A1ykp3+BQHt8XZdrx4UHSXUhjb9UlJ7F5bhXrTzmtq/M/A6TSKZoMfuftrpdTygT",
	"v17HPVAWPGrcarvT9cBpMMkT6wetLjekrysgXaHVA4iVzCBGxe0yyUnQHVDYVbkAliQVvtcgnUchcAGt",
	"KEEm2h4yd2DBkhuwu7UEi+EtI0MRBlxECi3iZIkHtX5kO040Q5Y5RnfHTGMMMSaGgY6YAHK5WiR3g29W",
	"4alfYm3sZgy6nZsunrHFbDzU02r0r9jEoEN5yk0G1t4kaCG3T9rsurXRHtAX+9bpRJZqp8vnnMG7YU2P",
	"rvpi6oEy7QNDFSFjnDJREaHQ5EpoODq9OrkEboVfcD1DfejIsN6F4UnivWKmDNn+9i+T/RrhTXI+NCzB",
	"dxY+lHG+NdxG1LqDeHF9BX2nrT7x+Nat9GzSfWO1EcQSrT00kNJHM8NQeDeRxPIrDdWhg9bwb+fH3cHL",
	"dg+urEhaz9RiGue7hsL9/OIrDUM2xy4TywVbQh+sVWYqLnzEXFtPsJjnQ20CpsszYyWBKWvGXZBsSyTT",
	"S7m2LPngIFWT/d6ca8Uy3LE1K2HQz4piNs7atJ9XChuOl5KyQW6vZNZNcI4JtOwDbUBhFEdNJ6SIgxaQ",
	"s4qgQ8uJgNu5UFy+fXsF3GhMJlZ2eZolPOLm0LtbGgRqQ4erGPPH948SrFxjGS1yG08KfBjXQR0pcpZl",
	"dgNqWchmOmpBYxcZugvUFgT7bVi6FKvDJtavFfh2Ehz8ePfKazPedu4H0u7B97ed4Jpk5E7fc6ufZl1P",
	"1eCrHYLCLCnjShYGK6Rz/YCIvJuraW/qpG4zDp8Jve7BI78SP9xz/t4NT8QcE5k1wK93OB7K6AaNtdfC",
	"APonoVWPwb3o7XqdOKLHRmAVE3AdCmtiMIY5qjEzPKXoU8qt3nab8r20u6UNjMkYcRGKMYtuUMR9a8qU",
	"YEl/oWf5uF9M3ZvKMoZ1NYSY68wpb4qGCS5gomj34r5WUT/h436ucYhacymGSxH1jG7SqUT5ilJ1rxww",
	"rflUYOzP0EFEScLyo+du8TFGMuDFx1TO6YM7qLV3/RfV4/6L4gXDpro2tjfMB9421r4pMINVvQX8so+Z",
	"XDfaAqn4lIsPfnUf+D0lJP45F39371IuiaLzuaHpekA5olC4WSh45VJ/3dobxGANrYLw33VCsU5xuwfH",
	"ZFY18KmQCou3FjOpMRQbxDvL7U44V0DRV2eH9zy1oZjwxKDy2aaGM7hMJGvgwomduaszjPiER+CfOwQ9",
	"YxlCjAZVyj3M8HLf2ziHTqqauF7N3HwonSp1Gen4oiKyOef/UNWykVG9O6VTkPHKielWMrYqMoVRrjSf",
	"14ncVqLhialeuYuiN/acbGdLLU55Z4j2ceKm74bWHNy3V7/WKJQu8tOaiwe6m27N9wnGr1vzViq3E3S3",
	"XDyQnF8qPk+/R00SuTL2XXURjkMOvzydmD4vdvF++rG3gts1wrq7vu4wN8Vuy+fvnHvobPLFVkNCBRRe",
	"2/uqyzXjWAtUFhNYgriYyM3xXBgLfri6uoCji7MeFAWe3hU9AAa+wGvGVNy1jlnsylZucOkMljXxvVAU",
	"Dj6LY4fHqhQOMaCbcG2qpCDhroUEFqdclF/rULSqzK4z5B2Y5EkCCrvEojZYVGexAaVGaSAXJxz0QhGK",
	"ocxV5HIFKjezAx8eUjI36MN2gB8zqVFDwufoIypc+6T70cVZd7BjTfxRHNtpmH93hqqKFDILN2dMxAkq",
	"iFhuR2PkattBKFsaChfglCzjxLgpChgaxSMzpE07s6jUctlPulvgCnfwi805ujgLOsEclXZ7Nujt9Aak",
	"PTIULOPBQbBHXzlJJxHtE1v7Hh+RCEvd4O8Um2ZZqgs2+uCc3cMtAbrV4BwLBYXlyqic3ZJaZM4l6Cx3",
	"C/naBZULDXopopmSQuY6Wdq3QlGEh3YHPl5Vj2xRLrgWMCriWAueJKAXnLC7BGbHDQV+xCj3cqSQpXYv",
	"s3oeHCqXpNpW664pFhkYK2Q3bkPs4aflnsWWZ1KbI8tef2Z9DTNq852Ml2vuJcuyhEf0cv/v2tWpVBXO",
	"dzm1azHY21unVpybSJu8O9h9/Nm8G0qzrcfC3AEEFkWYGYwPYT2o5zbLuxH2rdtOsD/45tGodFG6BtqO",
	"SvUAXANLFLJ4WS+JsJS8GOw9PSWvmGFjyxVOimWlZsGX8LTqFRZtMhe6SLwEV64uCZjTelJBLeBcrtJ7",
	"dVQJbEUxeG9H8adelzVTUzTbYpp6rSiqXkVTlgw4DeuCjc4rLxziUIxyjWtlWq32CGZS3kAmk8SHlaWA",
	"VObCbJxWlvkgqYt92nMLo3UnbgTrYYPipEYzJqYuEYmhWHCFzptqOrHfozuwvphs4xgNHk0s1uvWGgTk",
	"7gKmNWm4xEwqc8dWbRGEqGyGuFcEiiC1e6Vn11tEvfRqbGaHrKLbxhdgWa6djqZ8BFWcWzWPSWx38/rs",
	"EKSZoXJf6VDoGc9ctatGobk9ED6BpGFsla+iYghYYhkKj0PRuv5r9y+73cGOFxz3g50ztQdsXljNjS33",
	"DSFPuNt+hjs2OSqeWN1UFkOuSVPan3NfwlhtpX/tvcXGeVPORXGDemXLmJGpBVvJkoLNE62NVNg7oq/p",
	"+VC4vNbO3gEYTDP4PUyspYTfg3JpUP9FyxVHty1jHV6B1qvu/qB9ALm4EXIh/JbCv/77f2B/MAAu5izh",
	"8QdvB3uhsLpiMZN2i33xl1WIPojqkKshQEVVBHBxdHX8A2hMmTA8arS6eX1DH9/c1vdytSXp9stIEP0C",
	"ms2tocVoJn3sObNAUBuMS846Kzt4ett25rYZPP+hlbLEOmXWD5DxsrMqHh2QuenKSVcxMUUQeYqKR21n",
	"iZ+B2iGbI7g6YWjVUuwEztubitZKZsOxhBbJcbfgdrvpnFqd6xM+7rRSGHWzqIa+r1XjAXPKfcrnKGoe",
	"kwXyPfhuWShIaJWhrG+pSakdilpXRIG/9gff+IE/CGk+UAUD8El9whnTwMSyzEb5s+q0+h44Crv+4Ziz",
	"RE6hdX3WHV6cHMM//+HLa2G/DSxZsKUGjdZrq8izR6aG2iuGqtQbHLfr3YjS2pHMlj1XFcB1KDKmy16A",
	"n3LrPZStiqAlXF++7qKIJDlmzv3SMOqPQKPPcWrvjPhUd5GFm1lhEBKG//mam6KSyZDTYcf11atjtO6r",
	"xYvk2obC+7Yb2six6bRok6u3U/74JOUv1D1JDKnaJ8sg57YGyo3YyIYdmaEAkidoeUlrd+DzBCsU2yQL",
	"HixYodgmWfBwwQpFg2S5TGsD86rQcJ1j93YCvt8wBvvbjnn8BfUy15rcXWZmHQiDXi8MAHXEMmw7qvaf",
	"nip3OgjRucao53IGaxM7QV1XnnTqa1JbSOzz2SZvCArrdDqEfqGaUq4pEbVuofwrRXsRtK4uT066g5dt",
	"0nNCiq5brFcH6yenZrUKQ0XwsjEs5NIPwIRnoJ/SaaxPtd652/4ne55u3VkvWgdX+wZd7EbniSlE8m5t",
	"VwSCqGwb7M9dLshjIN0ZySThmkuhe1CjhFoeIUXm3Rqq2AiFa3o89VbAehhZrhBOhy5XrHI7xzoaHXkO",
	"+eqqbUEgP+pTAdKGPt0HodOdRyOhXoKx9ZgVeegvpuyciFox7ABPEpyyBKIZU7pTNMYaxeaoNEvaz6aD",
	"jreKLby9XJHbsnBMoZbJHF0kxFfjrKqA4liuqYD9duPhrmFS6pHcHgU+qnxH5wm6F6peRlKYGw3BLrpr",
	"+ci4sK66xTJf6Tq6KWrQMoUT/rEHZ2mWuFgWQWuqaygxWnE6Q/FZx9OlQVwbndehLtVDocBQjKmm4/ri",
	"1dHViYNbMDy5Iiq/7fV68O6Hk8sTR/Trsz+fwFeUGCOC+//xVdHMKgWG4ruT78/O4ezNm5NXZ3Y0o5jQ",
	"rgHsbiXxRhLQeAo9sdnM9Mw+7N1awpIHkUxdv++X1hKUINlQE18IIBUJ2HtUwJfXWBSzs2DgI9fGVeUU",
	"pD0LWiIZ+hysdOk7fxVYPbahMF90wP3x9XbNWbbyNAZQX3NtqEzdZ3W9XmmlaFjMDKtqrYUsHN52D75j",
	"VMLmq/rdIkJRJNlc/qIsPq+SZRajCrnuD5cJsK9dZJTFcShGf/zp2xGp69EfDZt+O/IVVExFM5dzZdRd",
	"bND6hFsip8VtIk+mMsoOqobNJtbKiUsyF/xc298Hsb++t7596l7AS8aKZm7EupSZve2lcR3vwopVdHGZ",
	"z8W7sA3uWqe2wLu1t3bvx77+vg8qL3cQjcrXyCp6t+hnVBLGS4PaEcHTFGPODBIQ6HrmbrNslZQ8Ffit",
	"1/A+M/Rd6c3bFFK6tuSLI9/CzXfR+MqsuQan3zIG9pmI3fZjoOHyzHr1vtd08kudTs0bDwzS0qi+65HX",
	"ql3gEh1ApkCU1RQJNUVWlQ6hqCVk7NmKEroapQZSnbpXclG09GhqRVP2t1VguT/Yr/pq3L1quoi1H8KL",
	"waD6tW4dyyNLtlOHoqh1NgsJlB7SsJB5EsMYIcGJAS4s7ObaCsX2sKcV/u+WZ3Hw2bGwZwBVdDLLmBO0",
	"ipSEZdu/R3yHhM5LWhXlaTRmHps0GvDmHXpcG751A2oBvy+/55vJ11UmN+OE1ZB+E13VI31/g+Lt+zJh",
	"u5G9rO3JnemCt5nhqcXZkQWOLjsfLWtdXPXmMQrgZwo1CtNZSQm557Fo7qP+bTZlXGiXcfI9aT77H4p6",
	"c9rl6fHe3t4350xIuL46bvfgrSjldu2SsCo/4C5jiGSMB1DrIhu5eN5os4VrVCi+sYyXhZf/S3vhenCB",
	"igziHEkdhoKNLVugFeUqgT6w3MjU60PFUcTJst0DV4oHxhoTn0bwzNLW5ZEZ+ymn63msfldWvrpG8ewQ",
	"UvYRErpTEXZfvHTWtpZumCFzuSGfbygaBVfSDbVrGXdfvNwsZn3/NOhqs0PqmUMGDX1P2461F5dDX+Dg",
	"7ePzBxTelKnuAn5Zqf3tmLXHRHTrbbFNyXX7iN+MUh/RGS47YguF8WxGlygmm5srBCkg5voGWk5wuqqM",
	"CbiqlzvLAGp5auuL3msvVtFlFW79xUak0Uv1YQ0m4n4V2nAYVVSF2v6g1CEkFAX+PiT6kNt1Vq5dPD89",
	"7pbeqwZuYIwTqSzMzTLCvj14x294N+HiBhR6wXh9dv7nYXfwddvO++rk9OTy8uSVhfQucPGy1o2+Rz57",
	"YYd0aaMgkU5Kqtum1uCzReNVOZvlXNeyJhQ1H66ID3vjEjEBCq15tTMUZpGJZVFOTyFfy5JQCKlS69qz",
	"u6K8RbvIE8Z4v6C6vscZ/m2FeAtR/61EeZ9Vcz9KdNf50oWH/m8U5a0HAZpjvHV9bfxlAXdWyEqB1MGP",
	"sYWItWrGokTat4JTyM1HBamp0ylaw6ZTjCEXltFW2RXd+BSF41Qe++mGi/gg9PHnMOj4sg2X0axuDbgN",
	"hayetiuxz/K4eJ6iPp3aLRO3PRhKZUCqGNUBsCSbsTEaq/dDMXYpU9p9LoCu7aPrEDplPs6peGcOenCt",
	"q8i1VY9jpkJxyhOkS15bCllkukyNpeLaOChwkTABg73u4OWWQDPd1/CEiovGb0pd50lC+/lswk1M8nfR",
	"FREZL+fUKVMK+xZYYqXR2URLutuhPtnHGUfFVDRbrhWUOenfqUs/rdgJ/2J7bsN5RN2xkiyOmDZVCX7R",
	"UQ0yQ6FJdEIx+mPVifxtmA8Ge1Ge85j+wtFGEV/rgpsJSxLYOfDWuMt0NxQsNzOpuHFopBqyctGclMTa",
	"K6xQjNbb6kfVpQK+MMw3CNApMe4SVbryJhS+GTwXhicWKEZSCIwMtZCtdGxNUVipRXc7cT4uu76cBuDa",
	"t4ctZjxyNYy5oFsw2TjBA0j4BKNllNBlAy13Iva7g/22a4vQMOov9AjmnIWCbifo/ZCPe7Rk6sr77uT0",
	"7eUJsIz3fnATnyqZvsk/OmVDsI00t6YLC+h0ZhhZkKWZ4XqyBNfRBq0wcBl7GtcRXXsjDNq0+LfUSQgo",
	"JlJFlKs/oGeOqOsHIpd2gQZaQ1Gtb7ftyvfcaBfMGFRCH8CPYWABXTKT2hz8ziqwMNjZ/bo36A16O/aL",
	"974g9W2G4ujizC2GosLnb68IAx4fnds/PYG+Nd+HD5jxilfZjU0diFcyKe6QyrOpYjHSHuoZu7Hmomvp",
	"3dnWRXCU8b/svNP3RW0uUHUNG7ugXSEypb70sLPlBXboLuGl+np/rXksM+NjNawskxVOWXyla+fh0MUo",
	"qgX4S3KKEnHuTJOXf3+nwpXLVADToXARjZX4xc7uHxxIKpga2x1OeRwnuGAW5Xsu7bW3F1Su3Eew/R/x",
	"qP9LFLt/2BLyqJmDHZfUWVNR1OvnG/qMjGSioVV1Cvldbteg6AYmA1ZrLVIlrq5r3VrrUXmVrZXz/k5v",
	"B66LOSr1uqBbMj523U2j3QWONb3uAToNTtvdJEBDlqLv4oXW9xLGXFi/RSr4izULMc7tWj9SVjNXSXAQ",
	"9FnG+/Md8hc9CY236yuKeIrYe+ulhOtq7xws2qwPfls8y5KqRZeO2j1NutXQritpc2iLHLpmzSpSV2aD",
	"AfNjeYv9qbEQrUsp92p1ZXVUAQRLRPhyBRr6sYvs/+bw1w0tAWttUUXw0gI2+vc43CI64P49Dip/QoUi",
	"whrTi96g97f/FwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
