// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FolderNodeKind.
const (
	Folder FolderNodeKind = "folder"
)

// Valid indicates whether the value is a known member of the FolderNodeKind enum.
func (e FolderNodeKind) Valid() bool {
	switch e {
	case Folder:
		return true
	default:
		return false
	}
}

// Defines values for MigrationStatusState.
const (
	Ok            MigrationStatusState = "ok"
	Rebuilding    MigrationStatusState = "rebuilding"
	RolledBack    MigrationStatusState = "rolled_back"
	Unrecoverable MigrationStatusState = "unrecoverable"
)

// Valid indicates whether the value is a known member of the MigrationStatusState enum.
func (e MigrationStatusState) Valid() bool {
	switch e {
	case Ok:
		return true
	case Rebuilding:
		return true
	case RolledBack:
		return true
	case Unrecoverable:
		return true
	default:
		return false
	}
}

// Defines values for NoteNodeKind.
const (
	NoteNodeKindNote NoteNodeKind = "note"
)

// Valid indicates whether the value is a known member of the NoteNodeKind enum.
func (e NoteNodeKind) Valid() bool {
	switch e {
	case NoteNodeKindNote:
		return true
	default:
		return false
	}
}

// Defines values for ReindexRequestMode.
const (
	Full        ReindexRequestMode = "full"
	Incremental ReindexRequestMode = "incremental"
)

// Valid indicates whether the value is a known member of the ReindexRequestMode enum.
func (e ReindexRequestMode) Valid() bool {
	switch e {
	case Full:
		return true
	case Incremental:
		return true
	default:
		return false
	}
}

// Defines values for StaleWriteErrorCode.
const (
	StaleWrite StaleWriteErrorCode = "stale_write"
)

// Valid indicates whether the value is a known member of the StaleWriteErrorCode enum.
func (e StaleWriteErrorCode) Valid() bool {
	switch e {
	case StaleWrite:
		return true
	default:
		return false
	}
}

// Defines values for WSEnvelopeEvent.
const (
	WSEnvelopeEventFolderCreated   WSEnvelopeEvent = "folder:created"
	WSEnvelopeEventFolderDeleted   WSEnvelopeEvent = "folder:deleted"
	WSEnvelopeEventFolderMoved     WSEnvelopeEvent = "folder:moved"
	WSEnvelopeEventMigrationStatus WSEnvelopeEvent = "migration:status"
	WSEnvelopeEventNoteCreated     WSEnvelopeEvent = "note:created"
	WSEnvelopeEventNoteDeleted     WSEnvelopeEvent = "note:deleted"
	WSEnvelopeEventNoteMoved       WSEnvelopeEvent = "note:moved"
	WSEnvelopeEventNoteUpdated     WSEnvelopeEvent = "note:updated"
	WSEnvelopeEventReindexComplete WSEnvelopeEvent = "reindex:complete"
	WSEnvelopeEventReindexStarted  WSEnvelopeEvent = "reindex:started"
	WSEnvelopeEventSessionAssigned WSEnvelopeEvent = "session:assigned"
	WSEnvelopeEventTagsUpdated     WSEnvelopeEvent = "tags:updated"
)

// Valid indicates whether the value is a known member of the WSEnvelopeEvent enum.
func (e WSEnvelopeEvent) Valid() bool {
	switch e {
	case WSEnvelopeEventFolderCreated:
		return true
	case WSEnvelopeEventFolderDeleted:
		return true
	case WSEnvelopeEventFolderMoved:
		return true
	case WSEnvelopeEventMigrationStatus:
		return true
	case WSEnvelopeEventNoteCreated:
		return true
	case WSEnvelopeEventNoteDeleted:
		return true
	case WSEnvelopeEventNoteMoved:
		return true
	case WSEnvelopeEventNoteUpdated:
		return true
	case WSEnvelopeEventReindexComplete:
		return true
	case WSEnvelopeEventReindexStarted:
		return true
	case WSEnvelopeEventSessionAssigned:
		return true
	case WSEnvelopeEventTagsUpdated:
		return true
	default:
		return false
	}
}

// CreateFolderRequest defines model for CreateFolderRequest.
type CreateFolderRequest struct {
	// Name New folder basename (single path segment, no `/`).
	Name string `json:"name"`

	// ParentPath Canonical relative path under notes/ to the parent folder, or ""
	// for the vault root.
	ParentPath string `json:"parent_path"`
}

// CreateNoteRequest defines model for CreateNoteRequest.
type CreateNoteRequest struct {
	// ParentPath Canonical relative path under notes/ to the parent folder, or ""
	// for the vault root. NFC + lowercase per DATA-11; the server
	// re-canonicalizes defensively.
	ParentPath string `json:"parent_path"`

	// Title Note title (basename without `.md`); the server appends `.md`.
	Title string `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FolderNode defines model for FolderNode.
type FolderNode struct {
	// Children ONLY populated when this FolderNode appears inside a Tree response.
	// Empty (or omitted) when used as a standalone response (POST /folders,
	// POST /folders/move).
	Children *[]TreeNode `json:"children,omitempty"`

	// Kind Discriminator value identifying this node as a folder.
	Kind FolderNodeKind `json:"kind"`

	// Name Basename (last path segment).
	Name string `json:"name"`

	// Path Canonical relative path under notes/ (NFC + lowercase per DATA-11)
	Path string `json:"path"`
}

// FolderNodeKind Discriminator value identifying this node as a folder.
type FolderNodeKind string

// MigrationStatus defines model for MigrationStatus.
type MigrationStatus struct {
	// FailedMigration Filename of the migration that triggered Path 1 (only set when state=rolled_back)
	FailedMigration *string `json:"failed_migration,omitempty"`

	// LogsPath Absolute path to the structured log file (only set when state in {rolled_back, unrecoverable})
	LogsPath *string `json:"logs_path,omitempty"`

	// NotesIndexed Count of rows currently in the `notes` table (informational)
	NotesIndexed *int `json:"notes_indexed,omitempty"`

	// State Current migration runner state. Surfaces the three-path resilience
	// model from DESIGN.md §4.4.
	//   - "ok"            — schema is current; no action required
	//   - "rolled_back"   — Path 1 fired; previous schema active; banner shown (UX-03)
	//   - "rebuilding"    — Path 2 in progress; UI shows ReindexProgress overlay
	//   - "unrecoverable" — Path 3 fired; static error page is served and the SPA cannot reach this endpoint (documented for future use)
	State MigrationStatusState `json:"state"`
}

// MigrationStatusState Current migration runner state. Surfaces the three-path resilience
// model from DESIGN.md §4.4.
//   - "ok"            — schema is current; no action required
//   - "rolled_back"   — Path 1 fired; previous schema active; banner shown (UX-03)
//   - "rebuilding"    — Path 2 in progress; UI shows ReindexProgress overlay
//   - "unrecoverable" — Path 3 fired; static error page is served and the SPA cannot reach this endpoint (documented for future use)
type MigrationStatusState string

// MoveFolderRequest defines model for MoveFolderRequest.
type MoveFolderRequest struct {
	// NewPath New canonical relative path under notes/ for the folder.
	NewPath string `json:"new_path"`

	// OldPath Current canonical relative path under notes/ for the folder.
	OldPath string `json:"old_path"`
}

// MoveNoteRequest defines model for MoveNoteRequest.
type MoveNoteRequest struct {
	// NewPath New canonical relative path under notes/ (with `.md` extension).
	NewPath string `json:"new_path"`
}

// Note defines model for Note.
type Note struct {
	// Content Raw markdown content of the note
	Content string             `json:"content"`
	Id      openapi_types.UUID `json:"id"`

	// Path Canonicalized relative path under notes/ (NFC + lowercase per DATA-11)
	Path string `json:"path"`

	// UpdatedAt Wall-clock UTC time of the last successful write
	UpdatedAt time.Time `json:"updated_at"`
}

// NoteList defines model for NoteList.
type NoteList struct {
	Notes []NoteSummary `json:"notes"`
}

// NoteNode defines model for NoteNode.
type NoteNode struct {
	Id openapi_types.UUID `json:"id"`

	// Kind Discriminator value identifying this node as a note.
	Kind NoteNodeKind `json:"kind"`

	// Path Canonical relative path under notes/ (NFC + lowercase per DATA-11)
	Path string `json:"path"`

	// Title First-H1 title or filename without `.md`; never empty.
	Title string `json:"title"`

	// UpdatedAt Wall-clock UTC of last filesystem mtime observed by the indexer.
	UpdatedAt time.Time `json:"updated_at"`
}

// NoteNodeKind Discriminator value identifying this node as a note.
type NoteNodeKind string

// NoteSummary defines model for NoteSummary.
type NoteSummary struct {
	Id openapi_types.UUID `json:"id"`

	// Path Canonical relative path under notes/ (NFC + lowercase per DATA-11)
	Path string `json:"path"`

	// Title First-H1 title or filename without `.md`; never empty
	Title string `json:"title"`

	// UpdatedAt Wall-clock UTC of last filesystem mtime observed by the indexer
	UpdatedAt time.Time `json:"updated_at"`
}

// ReindexRequest defines model for ReindexRequest.
type ReindexRequest struct {
	// Mode "full"        — Path 2: drop derived tables, re-run all migrations on the new (clean) schema, walk every .md file
	// "incremental" — re-run the cheap mtime-based delta scan only (DATA-09)
	Mode *ReindexRequestMode `json:"mode,omitempty"`
}

// ReindexRequestMode "full"        — Path 2: drop derived tables, re-run all migrations on the new (clean) schema, walk every .md file
// "incremental" — re-run the cheap mtime-based delta scan only (DATA-09)
type ReindexRequestMode string

// ReindexResponse defines model for ReindexResponse.
type ReindexResponse struct {
	// NotesIndexed Count of rows in the `notes` table after the reindex completed (Phase 2 only — Phase 4 streams this via WS)
	NotesIndexed *int `json:"notes_indexed,omitempty"`

	// StartedAt Wall-clock UTC when the reindex began (Phase 2 returns AFTER it finishes; this is still the start time)
	StartedAt time.Time `json:"started_at"`
}

// StaleWriteError Returned by PUT /notes/{id} when If-Match does not match the
// current file's updated_at (SYNC-06). The client surfaces
// SYNC-05's Save-anyway / Discard banner using
// current_updated_at as the new comparator.
type StaleWriteError struct {
	Code             StaleWriteErrorCode `json:"code"`
	CurrentUpdatedAt time.Time           `json:"current_updated_at"`
	Message          string              `json:"message"`
}

// StaleWriteErrorCode defines model for StaleWriteError.Code.
type StaleWriteErrorCode string

// Tree defines model for Tree.
type Tree struct {
	// Root Top-level (root) entries — children of the vault root (notes/). The
	// ROOT itself is implicit; folders nest via children[].
	Root []TreeNode `json:"root"`
}

// TreeNode defines model for TreeNode.
type TreeNode struct {
	union json.RawMessage
}

// UpdateNoteRequest defines model for UpdateNoteRequest.
type UpdateNoteRequest struct {
	// Content New raw markdown content; replaces the entire file
	Content string `json:"content"`
}

// UpdateNoteResponse defines model for UpdateNoteResponse.
type UpdateNoteResponse struct {
	Id        openapi_types.UUID `json:"id"`
	Path      string             `json:"path"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// WSEnvelope WebSocket event envelope (DESIGN.md §5.2). The `event` enum is
// locked verbatim and mirrors the Go const block in
// backend/internal/wshub/envelope.go and the TS dispatch table
// in frontend/src/lib/useSessionSync.ts.
type WSEnvelope struct {
	Event WSEnvelopeEvent `json:"event"`

	// OriginSessionId UUID of the session that originated the mutation. Empty
	// string for server-originated events (reindex:*,
	// migration:status). Clients ignore events whose
	// origin_session_id matches their own (SYNC-03 origin
	// filter).
	OriginSessionId string `json:"origin_session_id"`

	// Payload Event-specific payload; shape determined by `event`.
	Payload interface{} `json:"payload"`
}

// WSEnvelopeEvent defines model for WSEnvelope.Event.
type WSEnvelopeEvent string

// WSFolderCreatedPayload defines model for WSFolderCreatedPayload.
type WSFolderCreatedPayload struct {
	Name string `json:"name"`
	Path string `json:"path"`
}

// WSFolderDeletedPayload defines model for WSFolderDeletedPayload.
type WSFolderDeletedPayload struct {
	Path      string `json:"path"`
	Recursive bool   `json:"recursive"`
}

// WSFolderMovedPayload defines model for WSFolderMovedPayload.
type WSFolderMovedPayload struct {
	NewPath string `json:"new_path"`
	OldPath string `json:"old_path"`
}

// WSNoteCreatedPayload defines model for WSNoteCreatedPayload.
type WSNoteCreatedPayload struct {
	Id        openapi_types.UUID `json:"id"`
	Path      string             `json:"path"`
	Title     string             `json:"title"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// WSNoteDeletedPayload defines model for WSNoteDeletedPayload.
type WSNoteDeletedPayload struct {
	Id   openapi_types.UUID `json:"id"`
	Path string             `json:"path"`
}

// WSNoteMovedPayload defines model for WSNoteMovedPayload.
type WSNoteMovedPayload struct {
	Id        openapi_types.UUID `json:"id"`
	NewPath   string             `json:"new_path"`
	OldPath   string             `json:"old_path"`
	Title     string             `json:"title"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// WSNoteUpdatedPayload defines model for WSNoteUpdatedPayload.
type WSNoteUpdatedPayload struct {
	Id        openapi_types.UUID `json:"id"`
	Path      string             `json:"path"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// WSReindexCompletePayload defines model for WSReindexCompletePayload.
type WSReindexCompletePayload struct {
	NotesIndexed int `json:"notes_indexed"`
}

// WSReindexStartedPayload Empty payload — server-originated.
type WSReindexStartedPayload = map[string]interface{}

// NoteId defines model for NoteId.
type NoteId = openapi_types.UUID

// DeleteFolderParams defines parameters for DeleteFolder.
type DeleteFolderParams struct {
	// Path Canonical relative path under notes/ (NFC + lowercase per DATA-11)
	Path string `form:"path" json:"path"`

	// Recursive When false (default), the server returns 409 folder_not_empty if the
	// folder has any children. The Phase 3 Delete-folder dialog (UI-SPEC
	// §Surface 4) always sets recursive=true after the user confirms the
	// content-count copy.
	Recursive *bool `form:"recursive,omitempty" json:"recursive,omitempty"`
}

// PutNoteByIdParams defines parameters for PutNoteById.
type PutNoteByIdParams struct {
	// IfMatch Optimistic concurrency comparator (SYNC-06). When present,
	// the server compares this value against the file's current
	// updated_at (RFC3339Nano UTC). On mismatch the server
	// returns 409 with `code: stale_write` and
	// `current_updated_at` in the body — the client surfaces
	// SYNC-05's Save-anyway / Discard banner. Permissive when
	// absent (curl / automation friendly). Server treats the
	// value as an opaque string round-trip; max length 256 chars.
	IfMatch *string `json:"If-Match,omitempty"`
}

// GetApiV1WsParams defines parameters for GetApiV1Ws.
type GetApiV1WsParams struct {
	// SessionId Per-tab UUID generated by the client (sessionStorage).
	// Server adopts this as the connection's session_id; the
	// handshake message echoes it for confirmation. Treated as
	// opaque; max length 128 chars enforced in middleware
	// (T-04-03).
	SessionId *openapi_types.UUID `form:"session_id,omitempty" json:"session_id,omitempty"`
}

// PostAdminReindexJSONRequestBody defines body for PostAdminReindex for application/json ContentType.
type PostAdminReindexJSONRequestBody = ReindexRequest

// PostFoldersJSONRequestBody defines body for PostFolders for application/json ContentType.
type PostFoldersJSONRequestBody = CreateFolderRequest

// PostFolderMoveJSONRequestBody defines body for PostFolderMove for application/json ContentType.
type PostFolderMoveJSONRequestBody = MoveFolderRequest

// PostNotesJSONRequestBody defines body for PostNotes for application/json ContentType.
type PostNotesJSONRequestBody = CreateNoteRequest

// PutNoteByIdJSONRequestBody defines body for PutNoteById for application/json ContentType.
type PutNoteByIdJSONRequestBody = UpdateNoteRequest

// PostNoteMoveJSONRequestBody defines body for PostNoteMove for application/json ContentType.
type PostNoteMoveJSONRequestBody = MoveNoteRequest

// AsFolderNode returns the union data inside the TreeNode as a FolderNode
func (t TreeNode) AsFolderNode() (FolderNode, error) {
	var body FolderNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFolderNode overwrites any union data inside the TreeNode as the provided FolderNode
func (t *TreeNode) FromFolderNode(v FolderNode) error {
	v.Kind = "folder"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFolderNode performs a merge with any union data inside the TreeNode, using the provided FolderNode
func (t *TreeNode) MergeFolderNode(v FolderNode) error {
	v.Kind = "folder"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNoteNode returns the union data inside the TreeNode as a NoteNode
func (t TreeNode) AsNoteNode() (NoteNode, error) {
	var body NoteNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoteNode overwrites any union data inside the TreeNode as the provided NoteNode
func (t *TreeNode) FromNoteNode(v NoteNode) error {
	v.Kind = "note"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNoteNode performs a merge with any union data inside the TreeNode, using the provided NoteNode
func (t *TreeNode) MergeNoteNode(v NoteNode) error {
	v.Kind = "note"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TreeNode) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t TreeNode) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "folder":
		return t.AsFolderNode()
	case "note":
		return t.AsNoteNode()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t TreeNode) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TreeNode) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Trigger a full or incremental re-index
	// (POST /admin/reindex)
	PostAdminReindex(w http.ResponseWriter, r *http.Request)
	// Report the migration runner state
	// (GET /admin/status)
	GetAdminStatus(w http.ResponseWriter, r *http.Request)
	// Delete a folder (TREE-06) — non-empty requires recursive=true
	// (DELETE /folders)
	DeleteFolder(w http.ResponseWriter, r *http.Request, params DeleteFolderParams)
	// Create a folder (TREE-04)
	// (POST /folders)
	PostFolders(w http.ResponseWriter, r *http.Request)
	// Rename or move a folder (TREE-05, TREE-07)
	// (POST /folders/move)
	PostFolderMove(w http.ResponseWriter, r *http.Request)
	// List all indexed notes (metadata only)
	// (GET /notes)
	GetNotes(w http.ResponseWriter, r *http.Request)
	// Create a new note (TREE-03)
	// (POST /notes)
	PostNotes(w http.ResponseWriter, r *http.Request)
	// Delete a note by UUID (TREE-06)
	// (DELETE /notes/{id})
	DeleteNoteById(w http.ResponseWriter, r *http.Request, id NoteId)
	// Read a note by UUID
	// (GET /notes/{id})
	GetNoteById(w http.ResponseWriter, r *http.Request, id NoteId)
	// Replace the content of a note by UUID
	// (PUT /notes/{id})
	PutNoteById(w http.ResponseWriter, r *http.Request, id NoteId, params PutNoteByIdParams)
	// Rename or move a note (TREE-05, TREE-07)
	// (POST /notes/{id}/move)
	PostNoteMove(w http.ResponseWriter, r *http.Request, id NoteId)
	// Return the full folder/file hierarchy under notes/ (TREE-01)
	// (GET /tree)
	GetTree(w http.ResponseWriter, r *http.Request)
	// WebSocket endpoint (HTTP/1.1 Upgrade)
	// (GET /ws)
	GetApiV1Ws(w http.ResponseWriter, r *http.Request, params GetApiV1WsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Trigger a full or incremental re-index
// (POST /admin/reindex)
func (_ Unimplemented) PostAdminReindex(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Report the migration runner state
// (GET /admin/status)
func (_ Unimplemented) GetAdminStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a folder (TREE-06) — non-empty requires recursive=true
// (DELETE /folders)
func (_ Unimplemented) DeleteFolder(w http.ResponseWriter, r *http.Request, params DeleteFolderParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a folder (TREE-04)
// (POST /folders)
func (_ Unimplemented) PostFolders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rename or move a folder (TREE-05, TREE-07)
// (POST /folders/move)
func (_ Unimplemented) PostFolderMove(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all indexed notes (metadata only)
// (GET /notes)
func (_ Unimplemented) GetNotes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new note (TREE-03)
// (POST /notes)
func (_ Unimplemented) PostNotes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a note by UUID (TREE-06)
// (DELETE /notes/{id})
func (_ Unimplemented) DeleteNoteById(w http.ResponseWriter, r *http.Request, id NoteId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read a note by UUID
// (GET /notes/{id})
func (_ Unimplemented) GetNoteById(w http.ResponseWriter, r *http.Request, id NoteId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Replace the content of a note by UUID
// (PUT /notes/{id})
func (_ Unimplemented) PutNoteById(w http.ResponseWriter, r *http.Request, id NoteId, params PutNoteByIdParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rename or move a note (TREE-05, TREE-07)
// (POST /notes/{id}/move)
func (_ Unimplemented) PostNoteMove(w http.ResponseWriter, r *http.Request, id NoteId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return the full folder/file hierarchy under notes/ (TREE-01)
// (GET /tree)
func (_ Unimplemented) GetTree(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// WebSocket endpoint (HTTP/1.1 Upgrade)
// (GET /ws)
func (_ Unimplemented) GetApiV1Ws(w http.ResponseWriter, r *http.Request, params GetApiV1WsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAdminReindex operation middleware
func (siw *ServerInterfaceWrapper) PostAdminReindex(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminReindex(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAdminStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFolder operation middleware
func (siw *ServerInterfaceWrapper) DeleteFolder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteFolderParams

	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "recursive" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "recursive", r.URL.Query(), &params.Recursive, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "recursive"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recursive", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFolder(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostFolders operation middleware
func (siw *ServerInterfaceWrapper) PostFolders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostFolders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostFolderMove operation middleware
func (siw *ServerInterfaceWrapper) PostFolderMove(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostFolderMove(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNotes operation middleware
func (siw *ServerInterfaceWrapper) GetNotes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNotes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostNotes operation middleware
func (siw *ServerInterfaceWrapper) PostNotes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostNotes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNoteById operation middleware
func (siw *ServerInterfaceWrapper) DeleteNoteById(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id NoteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNoteById(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNoteById operation middleware
func (siw *ServerInterfaceWrapper) GetNoteById(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id NoteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNoteById(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutNoteById operation middleware
func (siw *ServerInterfaceWrapper) PutNoteById(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id NoteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PutNoteByIdParams

	headers := r.Header

	// ------------- Optional header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = &IfMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutNoteById(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostNoteMove operation middleware
func (siw *ServerInterfaceWrapper) PostNoteMove(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id NoteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostNoteMove(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTree operation middleware
func (siw *ServerInterfaceWrapper) GetTree(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTree(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1Ws operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Ws(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1WsParams

	// ------------- Optional query parameter "session_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "session_id", r.URL.Query(), &params.SessionId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "session_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1Ws(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/reindex", wrapper.PostAdminReindex)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/status", wrapper.GetAdminStatus)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/folders", wrapper.DeleteFolder)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/folders", wrapper.PostFolders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/folders/move", wrapper.PostFolderMove)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/notes", wrapper.GetNotes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/notes", wrapper.PostNotes)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/notes/{id}", wrapper.DeleteNoteById)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/notes/{id}", wrapper.GetNoteById)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/notes/{id}", wrapper.PutNoteById)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/notes/{id}/move", wrapper.PostNoteMove)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tree", wrapper.GetTree)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ws", wrapper.GetApiV1Ws)
	})

	return r
}

type PostAdminReindexRequestObject struct {
	Body *PostAdminReindexJSONRequestBody
}

type PostAdminReindexResponseObject interface {
	VisitPostAdminReindexResponse(w http.ResponseWriter) error
}

type PostAdminReindex202JSONResponse ReindexResponse

func (response PostAdminReindex202JSONResponse) VisitPostAdminReindexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type PostAdminReindex409JSONResponse Error

func (response PostAdminReindex409JSONResponse) VisitPostAdminReindexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PostAdminReindex503JSONResponse Error

func (response PostAdminReindex503JSONResponse) VisitPostAdminReindexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminStatusRequestObject struct {
}

type GetAdminStatusResponseObject interface {
	VisitGetAdminStatusResponse(w http.ResponseWriter) error
}

type GetAdminStatus200JSONResponse MigrationStatus

func (response GetAdminStatus200JSONResponse) VisitGetAdminStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFolderRequestObject struct {
	Params DeleteFolderParams
}

type DeleteFolderResponseObject interface {
	VisitDeleteFolderResponse(w http.ResponseWriter) error
}

type DeleteFolder204Response struct {
}

func (response DeleteFolder204Response) VisitDeleteFolderResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteFolder400JSONResponse Error

func (response DeleteFolder400JSONResponse) VisitDeleteFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFolder404JSONResponse Error

func (response DeleteFolder404JSONResponse) VisitDeleteFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFolder409JSONResponse Error

func (response DeleteFolder409JSONResponse) VisitDeleteFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFolder500JSONResponse Error

func (response DeleteFolder500JSONResponse) VisitDeleteFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostFoldersRequestObject struct {
	Body *PostFoldersJSONRequestBody
}

type PostFoldersResponseObject interface {
	VisitPostFoldersResponse(w http.ResponseWriter) error
}

type PostFolders201JSONResponse FolderNode

func (response PostFolders201JSONResponse) VisitPostFoldersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostFolders400JSONResponse Error

func (response PostFolders400JSONResponse) VisitPostFoldersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostFolders409JSONResponse Error

func (response PostFolders409JSONResponse) VisitPostFoldersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PostFolderMoveRequestObject struct {
	Body *PostFolderMoveJSONRequestBody
}

type PostFolderMoveResponseObject interface {
	VisitPostFolderMoveResponse(w http.ResponseWriter) error
}

type PostFolderMove200JSONResponse FolderNode

func (response PostFolderMove200JSONResponse) VisitPostFolderMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostFolderMove400JSONResponse Error

func (response PostFolderMove400JSONResponse) VisitPostFolderMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostFolderMove404JSONResponse Error

func (response PostFolderMove404JSONResponse) VisitPostFolderMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PostFolderMove409JSONResponse Error

func (response PostFolderMove409JSONResponse) VisitPostFolderMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PostFolderMove500JSONResponse Error

func (response PostFolderMove500JSONResponse) VisitPostFolderMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetNotesRequestObject struct {
}

type GetNotesResponseObject interface {
	VisitGetNotesResponse(w http.ResponseWriter) error
}

type GetNotes200JSONResponse NoteList

func (response GetNotes200JSONResponse) VisitGetNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostNotesRequestObject struct {
	Body *PostNotesJSONRequestBody
}

type PostNotesResponseObject interface {
	VisitPostNotesResponse(w http.ResponseWriter) error
}

type PostNotes201JSONResponse NoteSummary

func (response PostNotes201JSONResponse) VisitPostNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostNotes400JSONResponse Error

func (response PostNotes400JSONResponse) VisitPostNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostNotes409JSONResponse Error

func (response PostNotes409JSONResponse) VisitPostNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteNoteByIdRequestObject struct {
	Id NoteId `json:"id"`
}

type DeleteNoteByIdResponseObject interface {
	VisitDeleteNoteByIdResponse(w http.ResponseWriter) error
}

type DeleteNoteById204Response struct {
}

func (response DeleteNoteById204Response) VisitDeleteNoteByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteNoteById404JSONResponse Error

func (response DeleteNoteById404JSONResponse) VisitDeleteNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteNoteById500JSONResponse Error

func (response DeleteNoteById500JSONResponse) VisitDeleteNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetNoteByIdRequestObject struct {
	Id NoteId `json:"id"`
}

type GetNoteByIdResponseObject interface {
	VisitGetNoteByIdResponse(w http.ResponseWriter) error
}

type GetNoteById200JSONResponse Note

func (response GetNoteById200JSONResponse) VisitGetNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNoteById404JSONResponse Error

func (response GetNoteById404JSONResponse) VisitGetNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PutNoteByIdRequestObject struct {
	Id     NoteId `json:"id"`
	Params PutNoteByIdParams
	Body   *PutNoteByIdJSONRequestBody
}

type PutNoteByIdResponseObject interface {
	VisitPutNoteByIdResponse(w http.ResponseWriter) error
}

type PutNoteById200JSONResponse UpdateNoteResponse

func (response PutNoteById200JSONResponse) VisitPutNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutNoteById400JSONResponse Error

func (response PutNoteById400JSONResponse) VisitPutNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutNoteById404JSONResponse Error

func (response PutNoteById404JSONResponse) VisitPutNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PutNoteById409JSONResponse StaleWriteError

func (response PutNoteById409JSONResponse) VisitPutNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PutNoteById500JSONResponse Error

func (response PutNoteById500JSONResponse) VisitPutNoteByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostNoteMoveRequestObject struct {
	Id   NoteId `json:"id"`
	Body *PostNoteMoveJSONRequestBody
}

type PostNoteMoveResponseObject interface {
	VisitPostNoteMoveResponse(w http.ResponseWriter) error
}

type PostNoteMove200JSONResponse NoteSummary

func (response PostNoteMove200JSONResponse) VisitPostNoteMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostNoteMove400JSONResponse Error

func (response PostNoteMove400JSONResponse) VisitPostNoteMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostNoteMove404JSONResponse Error

func (response PostNoteMove404JSONResponse) VisitPostNoteMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PostNoteMove409JSONResponse Error

func (response PostNoteMove409JSONResponse) VisitPostNoteMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PostNoteMove500JSONResponse Error

func (response PostNoteMove500JSONResponse) VisitPostNoteMoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetTreeRequestObject struct {
}

type GetTreeResponseObject interface {
	VisitGetTreeResponse(w http.ResponseWriter) error
}

type GetTree200JSONResponse Tree

func (response GetTree200JSONResponse) VisitGetTreeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTree500JSONResponse Error

func (response GetTree500JSONResponse) VisitGetTreeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetApiV1WsRequestObject struct {
	Params GetApiV1WsParams
}

type GetApiV1WsResponseObject interface {
	VisitGetApiV1WsResponse(w http.ResponseWriter) error
}

type GetApiV1Ws101Response struct {
}

func (response GetApiV1Ws101Response) VisitGetApiV1WsResponse(w http.ResponseWriter) error {
	w.WriteHeader(101)
	return nil
}

type GetApiV1Ws400Response struct {
}

func (response GetApiV1Ws400Response) VisitGetApiV1WsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Trigger a full or incremental re-index
	// (POST /admin/reindex)
	PostAdminReindex(ctx context.Context, request PostAdminReindexRequestObject) (PostAdminReindexResponseObject, error)
	// Report the migration runner state
	// (GET /admin/status)
	GetAdminStatus(ctx context.Context, request GetAdminStatusRequestObject) (GetAdminStatusResponseObject, error)
	// Delete a folder (TREE-06) — non-empty requires recursive=true
	// (DELETE /folders)
	DeleteFolder(ctx context.Context, request DeleteFolderRequestObject) (DeleteFolderResponseObject, error)
	// Create a folder (TREE-04)
	// (POST /folders)
	PostFolders(ctx context.Context, request PostFoldersRequestObject) (PostFoldersResponseObject, error)
	// Rename or move a folder (TREE-05, TREE-07)
	// (POST /folders/move)
	PostFolderMove(ctx context.Context, request PostFolderMoveRequestObject) (PostFolderMoveResponseObject, error)
	// List all indexed notes (metadata only)
	// (GET /notes)
	GetNotes(ctx context.Context, request GetNotesRequestObject) (GetNotesResponseObject, error)
	// Create a new note (TREE-03)
	// (POST /notes)
	PostNotes(ctx context.Context, request PostNotesRequestObject) (PostNotesResponseObject, error)
	// Delete a note by UUID (TREE-06)
	// (DELETE /notes/{id})
	DeleteNoteById(ctx context.Context, request DeleteNoteByIdRequestObject) (DeleteNoteByIdResponseObject, error)
	// Read a note by UUID
	// (GET /notes/{id})
	GetNoteById(ctx context.Context, request GetNoteByIdRequestObject) (GetNoteByIdResponseObject, error)
	// Replace the content of a note by UUID
	// (PUT /notes/{id})
	PutNoteById(ctx context.Context, request PutNoteByIdRequestObject) (PutNoteByIdResponseObject, error)
	// Rename or move a note (TREE-05, TREE-07)
	// (POST /notes/{id}/move)
	PostNoteMove(ctx context.Context, request PostNoteMoveRequestObject) (PostNoteMoveResponseObject, error)
	// Return the full folder/file hierarchy under notes/ (TREE-01)
	// (GET /tree)
	GetTree(ctx context.Context, request GetTreeRequestObject) (GetTreeResponseObject, error)
	// WebSocket endpoint (HTTP/1.1 Upgrade)
	// (GET /ws)
	GetApiV1Ws(ctx context.Context, request GetApiV1WsRequestObject) (GetApiV1WsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostAdminReindex operation middleware
func (sh *strictHandler) PostAdminReindex(w http.ResponseWriter, r *http.Request) {
	var request PostAdminReindexRequestObject

	var body PostAdminReindexJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAdminReindex(ctx, request.(PostAdminReindexRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAdminReindex")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAdminReindexResponseObject); ok {
		if err := validResponse.VisitPostAdminReindexResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminStatus operation middleware
func (sh *strictHandler) GetAdminStatus(w http.ResponseWriter, r *http.Request) {
	var request GetAdminStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminStatus(ctx, request.(GetAdminStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminStatusResponseObject); ok {
		if err := validResponse.VisitGetAdminStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteFolder operation middleware
func (sh *strictHandler) DeleteFolder(w http.ResponseWriter, r *http.Request, params DeleteFolderParams) {
	var request DeleteFolderRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteFolder(ctx, request.(DeleteFolderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteFolder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteFolderResponseObject); ok {
		if err := validResponse.VisitDeleteFolderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostFolders operation middleware
func (sh *strictHandler) PostFolders(w http.ResponseWriter, r *http.Request) {
	var request PostFoldersRequestObject

	var body PostFoldersJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostFolders(ctx, request.(PostFoldersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostFolders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostFoldersResponseObject); ok {
		if err := validResponse.VisitPostFoldersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostFolderMove operation middleware
func (sh *strictHandler) PostFolderMove(w http.ResponseWriter, r *http.Request) {
	var request PostFolderMoveRequestObject

	var body PostFolderMoveJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostFolderMove(ctx, request.(PostFolderMoveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostFolderMove")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostFolderMoveResponseObject); ok {
		if err := validResponse.VisitPostFolderMoveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNotes operation middleware
func (sh *strictHandler) GetNotes(w http.ResponseWriter, r *http.Request) {
	var request GetNotesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNotes(ctx, request.(GetNotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNotes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNotesResponseObject); ok {
		if err := validResponse.VisitGetNotesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostNotes operation middleware
func (sh *strictHandler) PostNotes(w http.ResponseWriter, r *http.Request) {
	var request PostNotesRequestObject

	var body PostNotesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostNotes(ctx, request.(PostNotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostNotes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostNotesResponseObject); ok {
		if err := validResponse.VisitPostNotesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteNoteById operation middleware
func (sh *strictHandler) DeleteNoteById(w http.ResponseWriter, r *http.Request, id NoteId) {
	var request DeleteNoteByIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteNoteById(ctx, request.(DeleteNoteByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteNoteById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteNoteByIdResponseObject); ok {
		if err := validResponse.VisitDeleteNoteByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNoteById operation middleware
func (sh *strictHandler) GetNoteById(w http.ResponseWriter, r *http.Request, id NoteId) {
	var request GetNoteByIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNoteById(ctx, request.(GetNoteByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNoteById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNoteByIdResponseObject); ok {
		if err := validResponse.VisitGetNoteByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutNoteById operation middleware
func (sh *strictHandler) PutNoteById(w http.ResponseWriter, r *http.Request, id NoteId, params PutNoteByIdParams) {
	var request PutNoteByIdRequestObject

	request.Id = id
	request.Params = params

	var body PutNoteByIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutNoteById(ctx, request.(PutNoteByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutNoteById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutNoteByIdResponseObject); ok {
		if err := validResponse.VisitPutNoteByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostNoteMove operation middleware
func (sh *strictHandler) PostNoteMove(w http.ResponseWriter, r *http.Request, id NoteId) {
	var request PostNoteMoveRequestObject

	request.Id = id

	var body PostNoteMoveJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostNoteMove(ctx, request.(PostNoteMoveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostNoteMove")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostNoteMoveResponseObject); ok {
		if err := validResponse.VisitPostNoteMoveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTree operation middleware
func (sh *strictHandler) GetTree(w http.ResponseWriter, r *http.Request) {
	var request GetTreeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTree(ctx, request.(GetTreeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTree")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTreeResponseObject); ok {
		if err := validResponse.VisitGetTreeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1Ws operation middleware
func (sh *strictHandler) GetApiV1Ws(w http.ResponseWriter, r *http.Request, params GetApiV1WsParams) {
	var request GetApiV1WsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1Ws(ctx, request.(GetApiV1WsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1Ws")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1WsResponseObject); ok {
		if err := validResponse.VisitGetApiV1WsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Hx7ciM3kvdVMvh9GyZn+dLD9lgKx4SslmztdKu1ojS9E66OJliVJDFCAWUAJTanQxF7iL3D3GOOsifZ",
	"QAL1IFmU1Lak9viPmZZUBSQyE5m/fNWnVqzSTEmU1rQOPrUyplmKFjX9dK4sniXuXwmaWPPMciVbB63r",
	"67NXoKZg5whSWYT2xZwZhB2YMwP4kcVWLEFJhP/97/8Bgwgm1szG84wlQC9zCbFKsNPqtrhbMWN23uq2",
	"JEuxddDiSavb0vhLzjUmrQOrc+y2TDzHlDlipkqnzLYOWnlOT9pl5t4yVnM5a93d3RUP0yGONTKLp0ok",
	"qC/xlxyNpZNqlaG2HOkhv/H6Oc9xAVN6ESbMoHsI2obLmUBwFIPBWYrSdkEqGA/GnX6r28KPLM2EI+hv",
	"zGSoNwnsOjajtB/o1Bu7HjOpJI+ZAI2CWX4bNsulI8Tx2wzAKuK+XygQ2QWlIWpFrUhOlaa/37JcWNBK",
	"2X4kV4jLtPobxtY08K/O+59XaA0Sel++oyZuEXckz2anMVuZ/CVODeenx/DvINQCdex0NEMNr46ujno7",
	"O4f0sEF9izqSGntxQQP/OxpIcIrS8FsUy23MG2wXseVWNKmUuy70N2iXOrXgdq5yC+N+mow7dbKAZRnK",
	"xPg/rapXgobPZI9Y85lS9MQ1ifFEa6U3Recuq/v/anep7IepymXSdPgUjWGzjTe8sXCnBZ7AMPzXo//Z",
	"d//Dih/DfzsPnosIqzZsOpK/+ufhBGvnmnORaJSbgnp7/vqvkKksF8xiAos5SrBzbqBajoTDtAEuDXc/",
	"wpVGBI0mU9JgP5InaWaX0FYaVMqtxaTjF8oNJsAMMDCWyYQJZyuL96B98XZ0BQOv3qYbyZWfB6m6xY7X",
	"SG4xpXP8f43T1kHr/w0qcz4INnDgiKLT35XMYVqzpfv5hssG+/6Ku59SLplVGm6ZyBF4gtLy6ZLLmeeD",
	"JA64M3jCSDllnjqp+N/UpFGpRrOl/aE0r4IZu2JcP8Oo/mq70r7HSnQ+7+av6ScxuNt6yHq+4TPNHMUj",
	"y2xuNhV1yrjA5ENaPLd50FMuPAuDYy4fBTtnFqzmsxlqTODCHX8H2kqKJRi0XiWNZRa/10q4bSYsvlk9",
	"93C498GymembX0QT84WamS2W/WhilMht4Hsw4cbqPLa5o0eoGUy5M4gNFDmk8KlGVRdyqTFWt6jZRODd",
	"KpWDa0M3BAd9L5+BsUqzGQ4cfUFmfaFmTUcgXfjAZYIfseFSHKtcWsdcrRYG4lw7gyqWjkB3oDG9Pgbr",
	"yII2lx6lcCWZWCFyZ3f/23J3Li3OULvt6bgN2/qNauLUuZSoPXv6MMr1lMVoiAg714g94rNGwwVHGWMk",
	"U5WggKlWKbw6GZ39eN5PE/jnP/b7+/1IAvQgaqmbqAW1/wi4kQEBXp720OEcFnsqgpIXC9RkRCu5BYKm",
	"Td1zh5BpvOUqN8W6bqFbPIQJ8+eZq4WE9vV/9YZ7nXJVnORcJFzOPHnlqruO75lWM43GHML1Gb1v4BJJ",
	"gBfhL+AURbBlsd6K8kStar29gkrHVh4DOj8IGZuhOz854wSYTIjNo4sjiJmUyoJGFs+9QUSZZIpLC+1E",
	"xbkzXZiAgyTT3Cm6M/odjyOClVQ3DuZWfCPQW5y31V0ltsGYrpkar0CN1kXdPgiAcbHl+joQHD/GiBbo",
	"q+YONs2mxEWPrGDDBVQi2QYOwyV4OjqUSLbQscbVkqhuxaNtPL4X/T4Bh9sEnQgKAn60Dp0q2enf56AG",
	"HiX20+TBk957PHe0JlgoLUq7eaRLtoCU6ZvE3enwVD1ibBI/T1bx4iPx4QPR4IO4gP8dk6fBBlWQ28ju",
	"bivPEgcmP7AGjr1jQvRioeIbuL46BssrT06QyORxjMZMcwELzYmD5cndqj33xoMy5jUwUghvha5tsn/N",
	"G3WaYo+DT48Dom6dUZ6mTC83sei6MtLK26hpBvNegR7UhyfBvI6+OuIlpX7/sqj0sTHnKdfG9n7aCXGn",
	"80gFVlyJPA9Boos50UUt/d+owGrq9dZtZZbGYgqpV+pJ8KaTJWm3B1xkp3+FQgd8Xddrz4VHaXWhjb9W",
	"lV4k5HjQrDyl2Fd2fociVik6zP4fW8OuZ9SJ327jHqkLATVu9d1psDcJTlkuHDnTXLg4aPW4Ef26AtIV",
	"Wj2ARKsMEtTcHZOCBNMFjT2dS2BCVPjegPIRhcQFtGOBTHYCZO7CgokbcNJagsPwjpGRjFpcxhod4mQi",
	"gNqwslsnniPLPKN7E2YwgQSFZWBiJoFCrjbp3fC7VXgajlhbuxmDbuemz2dscRuPjbQa4ys2tehRnvab",
	"gfM3Ah3kDsnoXX82kgH9Yt8FnchS4235LWfwblSzo6uxmH6kTofEUEXIBGdMVkRotLmWBo5Or04ugTvl",
	"l9zM0Rx6Mlx0YbkQISpm2pLv7/w63a8R3qTnI8sEvnPwoczzreE2otZfxIvrKxh4a/WJJ3f+pGfT3htn",
	"jSBR6PyhhZR+tHOMZAgTSS2/MlBdOmiP/np+3Bt+0+nDlVNJF5k6TONj10j6P3/9lYERu8Uek8sFW8IA",
	"nFdmOilixNy4SLDY50NtA2bKO+M0gWnnxn2SbEsmM2i5cSz54CFVk//e3GvFM9wjmpU06GdlMRt3bZLn",
	"lcaG66WVatDbK5X1BN6igLZ7oAMoreZo6IYUedACclYZdGh7FfCSi+Tl27dXwK1BMXW6y9NM8JjbwxBu",
	"GZBoLF2uYs2f3z9JsnKNZXTIbTwp8GFSB3VkyFmWOQGQCClHuYWOWtLYZ4buA7UFwUEMy3NfxiJs4uJa",
	"iW+nrYOf7z95bce77sNA2j/4/q7buiYduTf23BqnudBTN8Rqh6AxE2VeycFgjXSvH5GR93s1yaZO6jbn",
	"8JnQ6wE88hvxwwP3793oRN6iUFkD/HqHk5GKb9A6fy0tYHgS2vUc3Nf93WATx/TYGJxhAm4i6VwMJnCL",
	"esIsTyn7lHJnt71QflROWsbChJwRl5GcsPgGZTJwrkxLJgYLM88ng2Lr/kyVOayrESTcZN54UzZMcglT",
	"TdJLBkbHA8Eng9zgCI3hSo6WMu5b02RTifIVo+pfOWDG8JnEJNyhg5iKhOWPgbvFjwmSAy9+TNUt/eAv",
	"au3d8Ivq8fCL4gXLZqa2dnDMB8E31n5TYAZnegv45R6zuWn0BUrzGZcfwuk+8AdK4+E5n3/371ItibLz",
	"uaXt+kA1okj6XSh55Ut/vdobxGAD7YLwP3QjuU5xpw/H5FYN8JlUGou3FnNlMJIbxHvP7W8410DZV++H",
	"9wK1kZxyYVGHalPDHVwKxRq4cOJ27pkMYz7lMYTnDsHMWYaQoEWd8gAzgt73N+6h16omrlc7N19Kb0p9",
	"RTq5qIhsrvk/1rRsVFTvL+kUZLzyarqVjK2GTGOca8Nv60ROlHIBwTZiqlfuo+iNuyfb2VLLU96bon2a",
	"vOm7kXMHD8nqtzqFMkR+XnfxyHDTn/khxfhtZ95K5XaC7teLR5Lza9Xn+WXUpJEra9/XF+E55PHL86np",
	"y2KXEKcfBy+43SKsh+vrAXNT7rZ8/t69R94nX2x1JNRAEax96CZbc461RGWxgSOIy6naXM+nseCnq6sL",
	"OLo460PRuBZC0QNgEBq85kwnPReYJb5t5QaX3mE5F9+PZBHgsyTxeKwq4RADeoIbWxUFCXctFLAk5bL8",
	"tYlku6rsekfehWkuBGjsEYs64FCdwwZUGqWFfJ5w2I9kJEcq17GvFejczg9Cekir3GJI2wF+zJRBA4Lf",
	"YsiocBOK7kcXZ73hjnPxR0nitmHh3TnqKlPIHNycM5kI1BCz3K3GKNR2i1C1NJI+walYxolxM5QwsprH",
	"dkRCO3Oo1HE5bLpb4Ap/8QvhHF2ctbqtW9TGy2zY3+kPyXpkKFnGWwetPfqV13RS0QGxdRDwEamwMg3x",
	"TiE0x1JTsDEk55wMtyToVpNzLJKUliuzck4ktcycL9A57hb6tQs6lwbMUsZzraTKjVi6tyJZpId2hyFf",
	"Vc9sUS24ljAq8lgLLgSYBSfsroC5dSOJHzHOgx5pZKmTZVavg0MVklRideGaZrGFiUZ24wXiLj8d9yxx",
	"PFPGHjn2hjsbejPR2B9UslwLL1mWCR7Ty4O/Gd+nUnVu3hfUruVg7+68WfFhIgl5d7j79LuFMJR2W8+F",
	"+QsILI4xs5gcwnpSzwsrhBHurbtua3/43ZNR6bN0DbQdleYBuAEmNLJkWW+JcJR8Pdx7fkpeMcsmjiuc",
	"DMtKz0Jo4WnXOyw65C5MUXhpXfm+JGDe6ikNtYRzecoQ1TnvQje99d6tEm69KXumZmi35TTNWlNUvYum",
	"bBnwFtYnG31UXgTEkRznBtfatNqdMcyVuoFMCRHSykpCqnJpN24ry0KS1Oc+3b2F8XoQN4b1tEFxU+M5",
	"kzNfiMRILrhGH0013dgf0V/Y0Ey2cY2GT6YW631rDQpyfwPTmjZcYqa0vUdUWxQhJB+98Cmk3yzw0u9r",
	"nSHA/EYzfouy5r2dU+nDD0sI1R4Xdoew6vspE9TFU+vQLWzB/vC7sPAHqewHqqYBn9Y3nDMDTC7LzGg/",
	"kk7HvKLsgaewFx5OOBNqBu3rs97o4uQY/vmP0OoF+x1gYsGWBgw6BFGRZ3Ver43khqyTnHKdBozihd6L",
	"qcQSq2zZ9xUqbiKZMVP2pf6SO09WjgOAUXB9+bqHMlYEEjwUMDAejMFgyLeb4BhD2aXICM/ZLYJUMPrP",
	"19wWVXVLDtCtGzqpJuiglLNdBLMiGXDWhnZ7NvlQljBANbLw87OUYmlCgRhSjSiUAfe2IYUNnL6RH5yj",
	"BNInaAdN63Th8xQrkts0Cx6tWJHcplnweMWKZINm+ax/A/OqNEWdY2VxlZjS3Ux5vN8wZPvbrnniPfHw",
	"+f3fmbxlgicQIBG0U24MQS9m512IWv1+1AI0Mcuw46naf36q/O2g+pxv0n8pYFLb2CvquvGkW1/T2kJj",
	"Ox6xvIDEgiPwHdXQPh3BoDBNKTeUFF0HKeGVotUd2leXJye94TcdsnNSyZ4/bDAH6zen5rQKR/X+rrsl",
	"RPGpMGAyMDBs6S3Wp9ocx93gk7tPd/6uF2MsqzMsPo4wubCFSt5v7YqghFoIwf25x6VBaTjZzlgJwV1Y",
	"ZvpQo4TGbyBFFlAWVQ8j6QdwToMXYBohyzXC6cjXLXTu9nAMtBRqUn8VjAOHQqV/W0ASVn2mWKRpZuxu",
	"Nc3h5LoZoOw8GQn1cuDWa1bURL6YsfMq6tSwC1wInDHhkKo23WJIy2rmQnkmOi9mg463qi28vVzR27KJ",
	"QaNR4hY9Kg+V4VUTUFzLNROw32m83DVMSvM62zMSR1al7roKZz0cI/0L1VwNGcyN4TSfaXB8ZFxiEjkI",
	"hV+ZOrop+iEyjVP+sQ9nLkqluIpQNdXYSoxW3M5Iftb19Ck5P9IRbKhPO1JYGskJ1RevL14dXZ14uAWj",
	"kyui8vt+vw/vfjq5PPFEvz778wl8RUlaInjwb18Vg1VKYiR/OPnx7BzO3rw5eXXmVrOaSeOHEe43Em8U",
	"AY3nsBObjfWPshLDF7ISjjyIVepnz760laBk3YaZ+EIAqSgGPGACvrzFopZ/BwY+cmN9hbgg7UXQEunQ",
	"52ClyzCFpsHZsQ2D+XUX/D++3W45y7byxnzOa24stUyGCkOwK+0ULUuYZVXfn1RFwNvpww+M2ilCh6k/",
	"RCSLhK/PpZWNkFXi1mFUqdbj4TIZ+61P77AkieT4T798PyZzPf6TZbPvx6Gaz3Q89/l/RpNuFl1MuCVx",
	"cx7GeZ/NZJTd/A3CJtaqqS94FPxck++j2F+XbWjlfxDwkrOinRuxLlUJ7vppUse7sOIVfV7mc/EubIO7",
	"Lqgt8G7trd2HsW+YPadWRw/RqJWCvGIIi/6OWsFkadF4IniaYsKZRQICvcDcbZ6t0pLnAr/1frIXhr4r",
	"cyKbSkoj9F8c+RZh/pSjSGpuzTfb/54xcDuocecp0HB5Z4N532u6+aVNp0biRyZpadUwgcNrlVe4RA+Q",
	"KRHlLIWgAZ2q6hZJVoFqd7diQWP6NZDqzb1Wi6K93NBYhHZ/WwWW+8P9qsfbf7vEQC5vpFrIQ/h6OKz+",
	"WveO5ZUl32kiWfTd2YUCY5VGAwuViwQmCAKnFrh0sJsbpxTb055O+X9YniWtz86FvQCooptZ5pygHdhE",
	"bPvXyO+Q0gVNq7I8jc4sYJNGB94soaf14VsFUEv4fXmZr0FDlqwxuRknrKb0m+iqHhmErxTdve+2srxB",
	"Jhd5XSb3lgveZpanDmfHDjj6Jvx4WZsoqA8yUAI/02hQ2u5KScg/j8WgCc0Sshnj0viKU5iPCE3+kawP",
	"SlyeHu/t7X13zqSC66vjTh/eylJv1z5YU9UH/GBwrBI8gNpEw9jn88ab4wTjwvBNVLIsovxfO5fRhwvU",
	"5BBvkcxhJNnEsQXaca4FDIDlVqXBHmqOMhHLTh98WwhY50xCGSEwy7iQR2Xsl5w+FeHsu3b61bOaZ4eQ",
	"so8gUM7sHHa//sZ721q5YY7M14ZCvaEYWlkpN6Ts42taonWw+/U3m41V758HXW12679wyqChB3/btQ7q",
	"cgjenwb/+PIJhTdMTJVOsYJfTmt/P27tKRHd+ohWAz30SBBGaY/oDpfTWYXBeDGnSxSTz801gpKQcHMD",
	"ba84PV3mBKZmKcPXNTa9A02c1OvULhZ90F+sossq3fqrnUhjlBrSGkwmgyq14TGqrJoGw0WpQ0gomk1D",
	"SvQxX3pY+QTY+elxr4xeDXALE5wq7WBulhH27cM7fsN7gssb0BgU4/XZ+Z9HveG3Hbfvq5PTk8vLk1cO",
	"0vvExTe1ycg9itkLP2RKHwVCeS2pvnyyBp8dGq+6axzneo41kazFcEV+ODiXmEnQ6Nyr26Fwi0wui9ZO",
	"Svk6lkRSKp260J7dl+UtWpefMcf7Bc31A8Hw7yvFW6j67yXL+6KW+0myuz6WLiL0f6Esbz0J0Jzjrdtr",
	"GwZX723YUxJpmhQTBxERis8qle16YSyRUm4hK0gDRt7QWjabYQK5dIx2xq6YDKUsHLdz1PDphsvkIAr5",
	"56jVDW0bvqJZTbDeRVJVT7uTuGd5UjxPWZ9ubeL5rg8jpS0onaA+ACayOZugdXY/khNfMiXpcwn0CSka",
	"ze2W9Thv4r076MO1qTLXzjxOmI7kKRdIHxxsa2Sx7TE9UZob66HAhWAShnu94TdbEs00O/yMhovWbypd",
	"50KQPF9MuYlJ4btIRUYm6Dl1bZfKvgWWOG30PtGR7iU0IP8456iZjufLtYYyr/07de2nE3vlX2yvbfiI",
	"qDfRiiUxM7ZqBy2m+0BlKA2pTiTHf6qm4r6P8uFwL85zntC/cLzRxNe+4HbKhICdg+CNe8z0IslyO1ea",
	"W49GqiWrEM1rSWKCwYrkeH3Ec1wNuIbGsNCsSrfE+g/60ecXIhkGE3NpuXBAMVZSYmxpnGFlemCG0mkt",
	"+i9l5pNyAsFbAG7CqMJizmPfw5hL+iIbmwg8AMGnGC9jQYOvbX8j9nvD/Y5v0TUwHizMGG45iyRNyvZ/",
	"yid9OjJNiPxwcvr28gRYxvs/+Y1PtUrf5B+9sSHYRpbb0PAs3c4MYweyDLPcTJfgpyugHbV8xZ7W9UTX",
	"3ohaHTr8W5pqAZRTpWOq1R/QM0fUgQ6xL7tAA62RrM632/Hte361C2YtamkO4Oeo5QCdmCtjD/7gDFjU",
	"2tn9tj/sD/s77hfvQ0Pq2wzl0cWZPwxlhc/fXhEGPD46d/8MBIYx0ZA+YDYYXu0Em3oQr5UovmeSZzPN",
	"EiQZmjm7ce6i5+jd6WxrYs74X3bemYeyNheoe5ZNfNKuUJnSXgbY2Q4KO/IfhHRbBt1micpsyNWwsk1W",
	"emPxlandh0Ofo6gOED7YABjPlYfmTjGD/of53itfqQBmIukzGiv5i53dP3qQVDA1cRJOeZIIXDCH8gOX",
	"9jrbGypXZmO3fyi7lvLY2f3jlpRHzR3s+KLOmomiuZMwXGJVrISBdtW1HqTcqUHRDUwGrNbmrktcXbe6",
	"tTb48rOKTs8HO/0duC72qMzrgia2P/b8V+96C5wYej0AdFqcxN2kQCOWYpgog/aPCiZcurhFafiLcwsJ",
	"3rqzfqSqZq5F66A1YBkf3O5QvBhIaPzSs6aMp0xCtF5quKlk52HRZn/w2+JZJqpxMbpqDwyMVUv7DvnN",
	"pR1y6Nk1r0gTQg0OLKwVPPanxka0HpXcq9OV3VEFECwR4Tcr0DCsXVT/797f/V8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
