package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/matthewoden/jasper/backend/internal/graphql/generated"
	"github.com/matthewoden/jasper/backend/internal/graphql/model"
)

// FindBlobByID is the resolver for the findBlobByID field.
func (r *entityResolver) FindBlobByID(ctx context.Context, id string) (*model.Blob, error) {
	item, err := r.resolveItem(ctx, id)
	if err != nil {
		return nil, err
	}
	if blob, ok := item.(*model.Blob); ok {
		return blob, nil
	}
	ref := r.canonicalRef(id)
	return &model.Blob{ID: ref, Kind: model.ItemKindBlob, Status: model.ItemStatusUnknown, Title: ref, Paths: []string{}}, nil
}

// FindNoteByID is the resolver for the findNoteByID field.
func (r *entityResolver) FindNoteByID(ctx context.Context, id string) (*model.Note, error) {
	item, err := r.resolveItem(ctx, id)
	if err != nil {
		return nil, err
	}
	if note, ok := item.(*model.Note); ok {
		return note, nil
	}
	// A representation is the router's claim that the id exists, so an id
	// Jasper does not know is an UNKNOWN stub, never null: null breaks the
	// non-null title and takes the caller's whole items(ids) element with
	// it. jasperItem still answers null; there the caller asked, not asserted.
	ref := r.canonicalRef(id)
	return &model.Note{ID: ref, Kind: model.ItemKindNote, Status: model.ItemStatusUnknown, Title: ref}, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
