package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/matthewoden/jasper/backend/internal/graphql/generated"
	"github.com/matthewoden/jasper/backend/internal/graphql/model"
)

// FindBlobByID is the resolver for the findBlobByID field.
func (r *entityResolver) FindBlobByID(ctx context.Context, id string) (*model.Blob, error) {
	item, err := r.resolveItem(ctx, id)
	if err != nil {
		return nil, err
	}
	blob, _ := item.(*model.Blob)
	return blob, nil
}

// FindNoteByID is the resolver for the findNoteByID field.
func (r *entityResolver) FindNoteByID(ctx context.Context, id string) (*model.Note, error) {
	item, err := r.resolveItem(ctx, id)
	if err != nil {
		return nil, err
	}
	note, _ := item.(*model.Note)
	return note, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
