package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"path"

	"github.com/matthewoden/jasper/backend/internal/graphql/generated"
	"github.com/matthewoden/jasper/backend/internal/graphql/model"
	"github.com/matthewoden/jasper/backend/internal/notes"
)

// Body is the resolver for the body field.
func (r *noteResolver) Body(ctx context.Context, obj *model.Note) (*string, error) {
	if obj.Status != model.ItemStatusOk {
		return nil, nil
	}
	id, ok := noteID(obj.ID)
	if !ok {
		return nil, nil
	}
	note, err := r.Notes.Get(ctx, id)
	if err != nil {
		if errors.Is(err, notes.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &note.Content, nil
}

// Refs is the resolver for the refs field.
func (r *noteResolver) Refs(ctx context.Context, obj *model.Note) ([]string, error) {
	id, ok := noteID(obj.ID)
	if !ok || r.Blobs == nil {
		return []string{}, nil
	}
	rows, err := r.Blobs.RefsBySource(ctx, id)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(rows))
	for _, row := range rows {
		out = append(out, row.TargetRef)
	}
	return out, nil
}

// Backlinks is the resolver for the backlinks field.
func (r *noteResolver) Backlinks(ctx context.Context, obj *model.Note) ([]model.Backlink, error) {
	return r.backlinksFor(ctx, obj.ID)
}

// JasperItem is the resolver for the jasperItem field.
func (r *queryResolver) JasperItem(ctx context.Context, id string) (model.Item, error) {
	return r.resolveItem(ctx, id)
}

// JasperItems is the resolver for the jasperItems field.
func (r *queryResolver) JasperItems(ctx context.Context, ids []string) ([]model.Item, error) {
	out := make([]model.Item, 0, len(ids))
	for _, id := range ids {
		item, err := r.resolveItem(ctx, id)
		if err != nil {
			return nil, err
		}
		out = append(out, item)
	}
	return out, nil
}

// JasperBacklinks is the resolver for the jasperBacklinks field.
func (r *queryResolver) JasperBacklinks(ctx context.Context, id string) ([]model.Backlink, error) {
	return r.backlinksFor(ctx, r.canonicalRef(id))
}

// JasperSearch is the resolver for the jasperSearch field.
func (r *queryResolver) JasperSearch(ctx context.Context, q string, limit *int) ([]model.Item, error) {
	n := 20
	if limit != nil && *limit > 0 {
		n = min(*limit, 100)
	}
	out := []model.Item{}
	if r.Index == nil {
		return out, nil
	}

	var noteIDs []notes.ID
	hits, err := r.Index.SearchFTS(ctx, q, nil, n, "relevance")
	switch {
	case err == nil && q != "":
		for _, h := range hits {
			if id, perr := notes.ParseID(h.ID); perr == nil {
				noteIDs = append(noteIDs, id)
			}
		}
	default:
		// An empty or malformed query lists by title instead; FTS5 reports some
		// syntax errors as plain SQL errors, so any failure falls back.
		if err != nil && !errors.Is(err, notes.ErrFTSQuerySyntax) && r.Log != nil {
			r.Log.Debug("jasperSearch: fts failed; listing by title", "q", q, "err", err)
		}
		results, terr := r.Index.SearchTitles(ctx, q, min(n, 50))
		if terr != nil {
			return nil, terr
		}
		for _, res := range results {
			noteIDs = append(noteIDs, res.ID)
		}
	}
	for _, id := range noteIDs {
		info, err := r.Index.LookupItem(ctx, id.String())
		if err != nil {
			return nil, err
		}
		info.ID = notes.RefForNote(id)
		item, err := r.toItem(ctx, info)
		if err != nil {
			return nil, err
		}
		if item != nil {
			out = append(out, item)
		}
	}

	if r.Blobs != nil && q != "" {
		blobs, err := r.Blobs.SearchBlobNames(ctx, q, n)
		if err != nil {
			return nil, err
		}
		for _, b := range blobs {
			info := notes.ItemInfo{
				ID: notes.RefForBlob(b.ID), Kind: notes.ItemKindBlob, Status: notes.ItemStatusOK,
				Title: path.Base(b.Path), Path: b.Path,
			}
			item, err := r.toBlob(ctx, info)
			if err != nil {
				return nil, err
			}
			out = append(out, item)
		}
	}
	return out, nil
}

// ItemChanged is the resolver for the itemChanged field.
func (r *subscriptionResolver) ItemChanged(ctx context.Context) (<-chan *model.ItemChange, error) {
	if r.Events == nil {
		return nil, errors.New("subscriptions are not available")
	}
	ch, unsubscribe := r.Events.Subscribe()
	go func() {
		<-ctx.Done()
		unsubscribe()
	}()
	return ch, nil
}

// Note returns generated.NoteResolver implementation.
func (r *Resolver) Note() generated.NoteResolver { return &noteResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type (
	noteResolver         struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
