// Command strip-comments-go removes non-load-bearing // and /* */ comments
// from Go source files using the go/ast + go/printer toolchain.
//
// Preserved (never stripped):
//   - Package doc comment (the group immediately preceding `package X`)
//   - Exported-symbol godoc (FuncDecl, GenDecl, specs, struct/interface fields
//     whose declared name passes ast.IsExported)
//   - Compiler/tool directives: //go:..., // +build, //nolint, //lint:ignore,
//     //revive:..., //staticcheck:..., //line, // export, // extern
//   - Cgo preamble: /* ... */ group immediately preceding `import "C"`
//
// Stripped: everything else (plain // line comments and plain /* */ blocks,
// including trailing inline comments).
//
// Usage:
//   strip-comments-go --root <dir> [--dry]
//   strip-comments-go [--dry] file1.go file2.go ...
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var (
	dryRun bool
	root   string
)

// directiveRe matches compiler/linter directives that MUST be preserved.
// Matched against the comment text including the leading "//" or "/*".
var directiveRe = regexp.MustCompile(`^//(go:|line |export |extern |nolint|lint:ignore|revive:|staticcheck:|\+build|cgo )|^// \+build `)

// skipPathSubstrings — any file whose absolute path contains one of these is
// not modified. Suffix-based skips are handled separately.
var skipPathSubstrings = []string{
	"/node_modules/",
	"/vendor/",
	"/backend/internal/static/dist/",
	"/.planning/",
}

var skipSuffixes = []string{
	".gen.go",
}

// generatedHeaderRe — Go convention; if first 4 KiB contains this, file is generated.
var generatedHeaderRe = regexp.MustCompile(`Code generated by `)

type stats struct {
	scanned       int
	modified      int
	commentsRem   int
	commentsKept  int
	parseFailures int
}

func main() {
	flag.BoolVar(&dryRun, "dry", false, "report counts but do not write")
	flag.StringVar(&root, "root", "", "walk this directory recursively (skips node_modules, vendor, dist, .gen.go, generated files)")
	flag.Parse()

	var paths []string
	if root != "" {
		walkRoot := root
		_ = filepath.WalkDir(walkRoot, func(p string, d fs.DirEntry, err error) error {
			if err != nil {
				return nil
			}
			if d.IsDir() {
				if shouldSkipDir(p) {
					return fs.SkipDir
				}
				return nil
			}
			if !strings.HasSuffix(p, ".go") {
				return nil
			}
			if shouldSkipFile(p) {
				return nil
			}
			paths = append(paths, p)
			return nil
		})
	}
	paths = append(paths, flag.Args()...)

	st := &stats{}
	for _, p := range paths {
		processFile(p, st)
	}

	fmt.Fprintf(os.Stderr,
		"strip-comments-go: scanned=%d modified=%d removed=%d preserved=%d parse_failures=%d dry=%v\n",
		st.scanned, st.modified, st.commentsRem, st.commentsKept, st.parseFailures, dryRun,
	)
	if st.parseFailures > 0 {
		os.Exit(2)
	}
}

func shouldSkipDir(p string) bool {
	base := filepath.Base(p)
	switch base {
	case "node_modules", "vendor", "dist", ".planning", ".git":
		return true
	}
	for _, sub := range skipPathSubstrings {
		if strings.Contains(p+"/", sub) {
			return true
		}
	}
	return false
}

func shouldSkipFile(p string) bool {
	for _, sub := range skipPathSubstrings {
		if strings.Contains(p, sub) {
			return true
		}
	}
	for _, suf := range skipSuffixes {
		if strings.HasSuffix(p, suf) {
			return true
		}
	}
	// Inspect first 4 KiB for generated-file marker.
	f, err := os.Open(p)
	if err != nil {
		return false
	}
	defer f.Close()
	buf := make([]byte, 4096)
	n, _ := f.Read(buf)
	if generatedHeaderRe.Match(buf[:n]) {
		return true
	}
	return false
}

func processFile(path string, st *stats) {
	st.scanned++
	src, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "STRIP_GO_READ_ERROR: %s: %v\n", path, err)
		st.parseFailures++
		return
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, src, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "STRIP_GO_PARSE_ERROR: %s: %v\n", path, err)
		st.parseFailures++
		return
	}

	preserve := buildPreserveSet(file, fset, src)

	originalTotal := 0
	for _, g := range file.Comments {
		originalTotal += len(g.List)
	}

	var kept []*ast.CommentGroup
	keptComments := 0
	for _, g := range file.Comments {
		if preserve[g] {
			kept = append(kept, g)
			keptComments += len(g.List)
		}
	}

	file.Comments = kept
	clearDocCommentFields(file, preserve)

	removed := originalTotal - keptComments
	st.commentsRem += removed
	st.commentsKept += keptComments

	if removed == 0 {
		return
	}

	var buf bytes.Buffer
	cfg := &printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}
	if err := cfg.Fprint(&buf, fset, file); err != nil {
		fmt.Fprintf(os.Stderr, "STRIP_GO_PRINT_ERROR: %s: %v\n", path, err)
		st.parseFailures++
		return
	}
	out, err := format.Source(buf.Bytes())
	if err != nil {
		// format.Source failure on valid AST output is anomalous — surface
		// as a parse failure (the verify step will catch it via golangci-lint
		// too, but better to halt now).
		fmt.Fprintf(os.Stderr, "STRIP_GO_FORMAT_ERROR: %s: %v\n", path, err)
		st.parseFailures++
		return
	}
	out = collapseBlankLines(out)

	if bytes.Equal(out, src) {
		return
	}
	st.modified++
	if dryRun {
		return
	}
	tmp := path + ".strip.tmp"
	if err := os.WriteFile(tmp, out, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "STRIP_GO_WRITE_ERROR: %s: %v\n", path, err)
		st.parseFailures++
		return
	}
	if err := os.Rename(tmp, path); err != nil {
		fmt.Fprintf(os.Stderr, "STRIP_GO_RENAME_ERROR: %s: %v\n", path, err)
		st.parseFailures++
		return
	}
}

// buildPreserveSet returns the set of *ast.CommentGroup that must survive.
func buildPreserveSet(file *ast.File, fset *token.FileSet, src []byte) map[*ast.CommentGroup]bool {
	preserve := map[*ast.CommentGroup]bool{}

	// Package doc comment.
	if file.Doc != nil {
		preserve[file.Doc] = true
	}

	// Directive groups (any comment in the group that matches a directive
	// preserves the whole group — directives are sticky to the surrounding
	// commentary in many cases, e.g. a `//go:embed` line preceded by an
	// explanation).
	for _, g := range file.Comments {
		for _, c := range g.List {
			if directiveRe.MatchString(c.Text) {
				preserve[g] = true
				break
			}
		}
	}

	// Exported-symbol doc comments + cgo preamble.
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if d.Doc != nil && isExportedFuncDecl(d) {
				preserve[d.Doc] = true
			}
		case *ast.GenDecl:
			handleGenDecl(d, preserve, fset, src, file)
		}
	}

	// Struct/interface field docs (nested under exported types).
	ast.Inspect(file, func(n ast.Node) bool {
		switch t := n.(type) {
		case *ast.StructType:
			if t.Fields == nil {
				return true
			}
			for _, f := range t.Fields.List {
				if fieldHasExportedName(f) {
					if f.Doc != nil {
						preserve[f.Doc] = true
					}
					if f.Comment != nil {
						preserve[f.Comment] = true
					}
				}
			}
		case *ast.InterfaceType:
			if t.Methods == nil {
				return true
			}
			for _, f := range t.Methods.List {
				if fieldHasExportedName(f) {
					if f.Doc != nil {
						preserve[f.Doc] = true
					}
					if f.Comment != nil {
						preserve[f.Comment] = true
					}
				}
			}
		}
		return true
	})

	return preserve
}

func isExportedFuncDecl(fd *ast.FuncDecl) bool {
	if fd.Name == nil {
		return false
	}
	return ast.IsExported(fd.Name.Name)
}

func handleGenDecl(d *ast.GenDecl, preserve map[*ast.CommentGroup]bool, fset *token.FileSet, src []byte, file *ast.File) {
	// IMPORT block: handle cgo preamble + blank-import justification
	// comments (revive's `blank-imports` rule).
	if d.Tok == token.IMPORT {
		for _, spec := range d.Specs {
			is, ok := spec.(*ast.ImportSpec)
			if !ok {
				continue
			}
			if is.Path != nil && is.Path.Value == `"C"` && d.Doc != nil {
				preserve[d.Doc] = true
			}
			if is.Name != nil && is.Name.Name == "_" {
				if is.Doc != nil {
					preserve[is.Doc] = true
				}
				if is.Comment != nil {
					preserve[is.Comment] = true
				}
				preservePrecedingGroup(is.Pos(), file, preserve, fset)
			}
		}
		return
	}

	// For top-level GenDecls (TYPE, CONST, VAR), preserve d.Doc only if
	// at least one spec declares an exported name.
	if d.Doc != nil && genDeclHasExportedSpec(d) {
		preserve[d.Doc] = true
	}

	// Per-spec docs/comments.
	for _, spec := range d.Specs {
		switch s := spec.(type) {
		case *ast.TypeSpec:
			if s.Name != nil && ast.IsExported(s.Name.Name) {
				if s.Doc != nil {
					preserve[s.Doc] = true
				}
				if s.Comment != nil {
					preserve[s.Comment] = true
				}
			}
		case *ast.ValueSpec:
			anyExported := false
			for _, n := range s.Names {
				if ast.IsExported(n.Name) {
					anyExported = true
					break
				}
			}
			if anyExported {
				if s.Doc != nil {
					preserve[s.Doc] = true
				}
				if s.Comment != nil {
					preserve[s.Comment] = true
				}
			}
		}
	}
}

func genDeclHasExportedSpec(d *ast.GenDecl) bool {
	for _, spec := range d.Specs {
		switch s := spec.(type) {
		case *ast.TypeSpec:
			if s.Name != nil && ast.IsExported(s.Name.Name) {
				return true
			}
		case *ast.ValueSpec:
			for _, n := range s.Names {
				if ast.IsExported(n.Name) {
					return true
				}
			}
		}
	}
	return false
}

func fieldHasExportedName(f *ast.Field) bool {
	if len(f.Names) == 0 {
		// Embedded field; treat as exported if the type ident is exported.
		switch t := f.Type.(type) {
		case *ast.Ident:
			return ast.IsExported(t.Name)
		case *ast.StarExpr:
			if id, ok := t.X.(*ast.Ident); ok {
				return ast.IsExported(id.Name)
			}
		case *ast.SelectorExpr:
			return ast.IsExported(t.Sel.Name)
		}
		return false
	}
	for _, n := range f.Names {
		if ast.IsExported(n.Name) {
			return true
		}
	}
	return false
}

// clearDocCommentFields nulls out Doc/Comment fields on decls/specs/fields
// when those groups are not in the preserve set. This prevents go/printer
// from re-emitting them.
func clearDocCommentFields(file *ast.File, preserve map[*ast.CommentGroup]bool) {
	if file.Doc != nil && !preserve[file.Doc] {
		file.Doc = nil
	}
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if d.Doc != nil && !preserve[d.Doc] {
				d.Doc = nil
			}
		case *ast.GenDecl:
			if d.Doc != nil && !preserve[d.Doc] {
				d.Doc = nil
			}
			for _, spec := range d.Specs {
				switch s := spec.(type) {
				case *ast.TypeSpec:
					if s.Doc != nil && !preserve[s.Doc] {
						s.Doc = nil
					}
					if s.Comment != nil && !preserve[s.Comment] {
						s.Comment = nil
					}
				case *ast.ValueSpec:
					if s.Doc != nil && !preserve[s.Doc] {
						s.Doc = nil
					}
					if s.Comment != nil && !preserve[s.Comment] {
						s.Comment = nil
					}
				case *ast.ImportSpec:
					if s.Doc != nil && !preserve[s.Doc] {
						s.Doc = nil
					}
					if s.Comment != nil && !preserve[s.Comment] {
						s.Comment = nil
					}
				}
			}
		}
	}
	ast.Inspect(file, func(n ast.Node) bool {
		switch t := n.(type) {
		case *ast.StructType:
			if t.Fields == nil {
				return true
			}
			for _, f := range t.Fields.List {
				if f.Doc != nil && !preserve[f.Doc] {
					f.Doc = nil
				}
				if f.Comment != nil && !preserve[f.Comment] {
					f.Comment = nil
				}
			}
		case *ast.InterfaceType:
			if t.Methods == nil {
				return true
			}
			for _, f := range t.Methods.List {
				if f.Doc != nil && !preserve[f.Doc] {
					f.Doc = nil
				}
				if f.Comment != nil && !preserve[f.Comment] {
					f.Comment = nil
				}
			}
		}
		return true
	})
}

var (
	manyBlanksRe            = regexp.MustCompile(`\n{4,}`)
	blankAfterOpenBraceRe   = regexp.MustCompile(`\{\n(?:[ \t]*\n)+`)
	blankBeforeCloseBraceRe = regexp.MustCompile(`\n(?:[ \t]*\n)+([ \t]*\})`)
)

func collapseBlankLines(b []byte) []byte {
	out := manyBlanksRe.ReplaceAll(b, []byte("\n\n\n"))
	// gofumpt: no blank line directly after `{` opening a block.
	for {
		next := blankAfterOpenBraceRe.ReplaceAll(out, []byte("{\n"))
		if bytes.Equal(next, out) {
			break
		}
		out = next
	}
	// gofumpt: no blank line directly before `}` closing a block.
	out = blankBeforeCloseBraceRe.ReplaceAllFunc(out, func(m []byte) []byte {
		i := bytes.LastIndexByte(m, '}')
		j := i - 1
		for j >= 0 && (m[j] == ' ' || m[j] == '\t') {
			j--
		}
		return append([]byte{'\n'}, m[j+1:]...)
	})
	return out
}

// preservePrecedingGroup preserves the comment group, if any, whose End()
// is on the line immediately preceding `pos`. Used to keep comments that
// justify a blank `_ "pkg"` import for revive's blank-imports rule.
func preservePrecedingGroup(pos token.Pos, file *ast.File, preserve map[*ast.CommentGroup]bool, fset *token.FileSet) {
	posLine := fset.Position(pos).Line
	for _, g := range file.Comments {
		endLine := fset.Position(g.End()).Line
		if endLine == posLine-1 || endLine == posLine {
			preserve[g] = true
		}
	}
}
