/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/notes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the note (Phase 1 has exactly one — see scratchpad UUID in code) */
                id: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        /** Read a note by UUID */
        get: operations["getNoteById"];
        /** Replace the content of a note by UUID */
        put: operations["putNoteById"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Note: {
            /**
             * Format: uuid
             * @example 00000000-0000-4000-a000-000000000001
             */
            id: string;
            /**
             * @description Canonicalized relative path under notes/ (NFC + lowercase per DATA-11)
             * @example scratchpad.md
             */
            path: string;
            /** @description Raw markdown content of the note */
            content: string;
            /**
             * Format: date-time
             * @description Wall-clock UTC time of the last successful write
             */
            updated_at: string;
        };
        UpdateNoteRequest: {
            /** @description New raw markdown content; replaces the entire file */
            content: string;
        };
        UpdateNoteResponse: {
            /** Format: uuid */
            id: string;
            path: string;
            /** Format: date-time */
            updated_at: string;
        };
        Error: {
            /** @example not_found */
            code: string;
            /** @example no note with id 00000000-0000-4000-a000-000000000001 */
            message: string;
        };
    };
    responses: never;
    parameters: {
        /** @description UUID of the note (Phase 1 has exactly one — see scratchpad UUID in code) */
        NoteId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getNoteById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the note (Phase 1 has exactly one — see scratchpad UUID in code) */
                id: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Note found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Note not found (unknown UUID) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    putNoteById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the note (Phase 1 has exactly one — see scratchpad UUID in code) */
                id: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNoteRequest"];
            };
        };
        responses: {
            /** @description Note updated; atomic write committed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateNoteResponse"];
                };
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Note not found (unknown UUID) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Write failure on disk (atomic-rename or fsync error) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
