/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all indexed notes (metadata only)
         * @description List all indexed notes (metadata only — no content). Backed by the SQLite
         *     derived index (DATA-09). Phase 2 has no query parameters; Phase 7 will add
         *     `?q=` and `?tag=` for search and tag filtering.
         */
        get: operations["getNotes"];
        put?: never;
        /**
         * Create a new note (TREE-03)
         * @description Create a new note under {parent_path}/{title}.md. The server canonicalizes
         *     the resulting path (NFC + lowercase per DATA-11) and rejects case-insensitive
         *     collisions per DATA-12. parent_path "" means the vault root. The created
         *     file is empty (zero bytes) and immediately re-indexed.
         */
        post: operations["postNotes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the note (Phase 1 has exactly one — see scratchpad UUID in code) */
                id: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        /** Read a note by UUID */
        get: operations["getNoteById"];
        /** Replace the content of a note by UUID */
        put: operations["putNoteById"];
        post?: never;
        /**
         * Delete a note by UUID (TREE-06)
         * @description Delete the note identified by UUID. Removes the underlying `.md` file
         *     atomically and clears the SQLite index row in the same write transaction.
         *     404 when the UUID is unknown; 500 when the FS / SQLite operation fails
         *     and the two stores would be left inconsistent.
         */
        delete: operations["deleteNoteById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the note (Phase 1 has exactly one — see scratchpad UUID in code) */
                id: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rename or move a note (TREE-05, TREE-07)
         * @description Rename and/or move a note in a single atomic transaction. new_path is a
         *     canonical relative path under notes/; the server NFC-lowercases it before
         *     applying. Wiki-link rewrite (LINKS-07) is DEFERRED to Phase 6 — Phase 3 only
         *     updates the file location and the SQLite index row. Returns the post-move
         *     NoteSummary so the client can reconcile against any server-side path
         *     normalization.
         */
        post: operations["postNoteMove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the full folder/file hierarchy under notes/ (TREE-01)
         * @description Returns one nested tree document for the entire vault. The shape is a
         *     tagged union — TreeNode is either {kind:"folder", path, name, children[]}
         *     or {kind:"note", id, path, title, updated_at}. Sort order: alphabetical
         *     by name within each level, folders before notes. Used by the sidebar
         *     FileTree (react-arborist) — Plan 03-06.
         */
        get: operations["getTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a folder (TREE-04)
         * @description Create an empty folder under {parent_path}/{name}. The server
         *     canonicalizes the resulting path (NFC + lowercase per DATA-11) and
         *     rejects case-insensitive collisions. parent_path "" means the vault
         *     root. Folders are pure FS constructs — there is no `folders` table.
         */
        post: operations["postFolders"];
        /**
         * Delete a folder (TREE-06) — non-empty requires recursive=true
         * @description Delete the folder at the given canonical path. By default (recursive=false)
         *     the server returns 409 folder_not_empty if the folder has any children.
         *     The Phase 3 Delete-folder dialog (UI-SPEC §Surface 4) always sets
         *     recursive=true after the user confirms the content-count copy. Path is
         *     passed as a query parameter so URL-encoding handles `/` separators
         *     cleanly — folders have no SQLite identity and so cannot be addressed by
         *     UUID.
         */
        delete: operations["deleteFolder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/folders/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rename or move a folder (TREE-05, TREE-07)
         * @description Atomically renames/moves a folder and re-canonicalizes every contained
         *     note's path under the new prefix. Implementation note: folders are pure
         *     FS constructs — there is no `folders` table — so the SQLite update is a
         *     batch UPDATE notes SET path=... WHERE path LIKE 'old_prefix/%' inside one
         *     BEGIN IMMEDIATE transaction.
         */
        post: operations["postFolderMove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report the migration runner state
         * @description Returns the migration runner state for the UX-03 banner. The frontend
         *     `useMigrationStatus()` hook polls this on mount; Phase 4 will swap the
         *     client to a `migration:status` WebSocket event without changing the
         *     wire shape.
         */
        get: operations["getAdminStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read user configuration
         * @description Returns the current config.json contents (DESIGN.md §11).
         *     Phase 5 wires only the `theme` field to UI; other fields
         *     ship with sensible defaults but are not yet surfaced
         *     (UX-V2-01 will surface them in v2).
         */
        get: operations["getConfig"];
        /**
         * Replace user configuration (whole-document)
         * @description Writes config.json atomically via fsstore.AtomicWrite
         *     (DATA-13: temp + fsync + rename + fsync(parent)).
         *     Strict (D-40): unknown fields → 400 invalid_request.
         *     The whole document is replaced — there is no PATCH semantic.
         */
        put: operations["putConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket endpoint (HTTP/1.1 Upgrade)
         * @description Server-broadcast WebSocket. Client opens with
         *     `?session_id=<uuid>` query parameter (Pitfall 1: client-as-
         *     authoritative session_id). Server responds with a
         *     `session:assigned` envelope confirming the id, then streams
         *     events until disconnect.
         *
         *     oapi-codegen generates a stub handler for this route which is
         *     unreachable: lifecycle.go (Plan 04-04) mounts `/ws` via
         *     wshub.Hub.ServeHTTP BEFORE api.HandlerFromMux. The path exists
         *     in the spec to satisfy API-01 ("every HTTP route in the spec").
         *
         *     Origin enforcement: the Accept call in wshub.Hub.ServeHTTP
         *     (Plan 04-02) sets OriginPatterns: ["localhost:*", "127.0.0.1:*"].
         *     The OpenAPI spec does NOT and CANNOT enforce origin — that is a
         *     runtime control on the upgrade handshake (T-04-01).
         */
        get: operations["getApiV1Ws"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a full or incremental re-index
         * @description Phase 2 backs DATA-10: drop the derived tables, re-run migrations on a
         *     clean schema, and walk every `.md` file. Phase 2 runs synchronously and
         *     returns 202 only after the rebuild finishes; Phase 4 will switch to async
         *     execution streaming progress over WebSocket without a contract break.
         */
        post: operations["postAdminReindex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Note: {
            /**
             * Format: uuid
             * @example 00000000-0000-4000-a000-000000000001
             */
            id: string;
            /**
             * @description Canonicalized relative path under notes/ (NFC + lowercase per DATA-11)
             * @example scratchpad.md
             */
            path: string;
            /** @description Raw markdown content of the note */
            content: string;
            /**
             * Format: date-time
             * @description Wall-clock UTC time of the last successful write
             */
            updated_at: string;
        };
        UpdateNoteRequest: {
            /** @description New raw markdown content; replaces the entire file */
            content: string;
        };
        UpdateNoteResponse: {
            /** Format: uuid */
            id: string;
            path: string;
            /** Format: date-time */
            updated_at: string;
        };
        NoteSummary: {
            /** Format: uuid */
            id: string;
            /**
             * @description Canonical relative path under notes/ (NFC + lowercase per DATA-11)
             * @example scratchpad.md
             */
            path: string;
            /**
             * @description First-H1 title or filename without `.md`; never empty
             * @example Welcome to Jasper
             */
            title: string;
            /**
             * Format: date-time
             * @description Wall-clock UTC of last filesystem mtime observed by the indexer
             */
            updated_at: string;
        };
        NoteList: {
            notes: components["schemas"]["NoteSummary"][];
        };
        MigrationStatus: {
            /**
             * @description Current migration runner state. Surfaces the three-path resilience
             *     model from DESIGN.md §4.4.
             *       - "ok"            — schema is current; no action required
             *       - "rolled_back"   — Path 1 fired; previous schema active; banner shown (UX-03)
             *       - "rebuilding"    — Path 2 in progress; UI shows ReindexProgress overlay
             *       - "unrecoverable" — Path 3 fired; static error page is served and the SPA cannot reach this endpoint (documented for future use)
             * @enum {string}
             */
            state: "ok" | "rolled_back" | "rebuilding" | "unrecoverable";
            /**
             * @description Filename of the migration that triggered Path 1 (only set when state=rolled_back)
             * @example 003_tags.sql
             */
            failed_migration?: string;
            /**
             * @description Absolute path to the structured log file (only set when state in {rolled_back, unrecoverable})
             * @example /Users/me/.jasper/storage/logs/jasper.log
             */
            logs_path?: string;
            /**
             * @description Count of rows currently in the `notes` table (informational)
             * @example 1247
             */
            notes_indexed?: number;
        };
        ReindexRequest: {
            /**
             * @description "full"        — Path 2: drop derived tables, re-run all migrations on the new (clean) schema, walk every .md file
             *     "incremental" — re-run the cheap mtime-based delta scan only (DATA-09)
             * @default full
             * @enum {string}
             */
            mode: "full" | "incremental";
        };
        ReindexResponse: {
            /**
             * Format: date-time
             * @description Wall-clock UTC when the reindex began (Phase 2 returns AFTER it finishes; this is still the start time)
             */
            started_at: string;
            /** @description Count of rows in the `notes` table after the reindex completed (Phase 2 only — Phase 4 streams this via WS) */
            notes_indexed?: number;
        };
        CreateNoteRequest: {
            /**
             * @description Canonical relative path under notes/ to the parent folder, or ""
             *     for the vault root. NFC + lowercase per DATA-11; the server
             *     re-canonicalizes defensively.
             * @example projects/jasper
             */
            parent_path: string;
            /**
             * @description Note title (basename without `.md`); the server appends `.md`.
             * @example design-notes
             */
            title: string;
        };
        MoveNoteRequest: {
            /**
             * @description New canonical relative path under notes/ (with `.md` extension).
             * @example projects/jasper/design.md
             */
            new_path: string;
        };
        CreateFolderRequest: {
            /**
             * @description Canonical relative path under notes/ to the parent folder, or ""
             *     for the vault root.
             * @example projects
             */
            parent_path: string;
            /**
             * @description New folder basename (single path segment, no `/`).
             * @example jasper
             */
            name: string;
        };
        MoveFolderRequest: {
            /**
             * @description Current canonical relative path under notes/ for the folder.
             * @example projects/old-name
             */
            old_path: string;
            /**
             * @description New canonical relative path under notes/ for the folder.
             * @example projects/new-name
             */
            new_path: string;
        };
        FolderNode: {
            /**
             * @description Discriminator value identifying this node as a folder. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            kind: "folder";
            /**
             * @description Canonical relative path under notes/ (NFC + lowercase per DATA-11)
             * @example projects/jasper
             */
            path: string;
            /**
             * @description Basename (last path segment).
             * @example jasper
             */
            name: string;
            /**
             * @description ONLY populated when this FolderNode appears inside a Tree response.
             *     Empty (or omitted) when used as a standalone response (POST /folders,
             *     POST /folders/move).
             */
            children?: components["schemas"]["TreeNode"][];
        };
        NoteNode: {
            /**
             * @description Discriminator value identifying this node as a note. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            kind: "note";
            /** Format: uuid */
            id: string;
            /** @description Canonical relative path under notes/ (NFC + lowercase per DATA-11) */
            path: string;
            /** @description First-H1 title or filename without `.md`; never empty. */
            title: string;
            /**
             * Format: date-time
             * @description Wall-clock UTC of last filesystem mtime observed by the indexer.
             */
            updated_at: string;
        };
        TreeNode: components["schemas"]["FolderNode"] | components["schemas"]["NoteNode"];
        Tree: {
            /**
             * @description Top-level (root) entries — children of the vault root (notes/). The
             *     ROOT itself is implicit; folders nest via children[].
             */
            root: components["schemas"]["TreeNode"][];
        };
        Config: {
            /** @default Jasper */
            appName: string;
            /**
             * @default dark
             * @enum {string}
             */
            theme: "dark" | "light";
            dailyNotes: {
                /** @default daily */
                folder: string;
                /** @default  */
                template: string;
            };
            editor: {
                /** @default 15 */
                fontSize: number;
                /** @default 1.6 */
                lineHeight: number;
                /** @default false */
                vimMode: boolean;
            };
        };
        Error: {
            /** @example not_found */
            code: string;
            /** @example no note with id 00000000-0000-4000-a000-000000000001 */
            message: string;
        };
        /**
         * @description WebSocket event envelope (DESIGN.md §5.2). The `event` enum is
         *     locked verbatim and mirrors the Go const block in
         *     backend/internal/wshub/envelope.go and the TS dispatch table
         *     in frontend/src/lib/useSessionSync.ts.
         */
        WSEnvelope: {
            /** @enum {string} */
            event: "session:assigned" | "note:created" | "note:updated" | "note:deleted" | "note:moved" | "folder:created" | "folder:deleted" | "folder:moved" | "tags:updated" | "reindex:started" | "reindex:complete" | "migration:status";
            /**
             * @description UUID of the session that originated the mutation. Empty
             *     string for server-originated events (reindex:*,
             *     migration:status). Clients ignore events whose
             *     origin_session_id matches their own (SYNC-03 origin
             *     filter).
             */
            origin_session_id: string;
            /** @description Event-specific payload; shape determined by `event`. */
            payload: unknown;
        };
        WSNoteCreatedPayload: {
            /** Format: uuid */
            id: string;
            path: string;
            title: string;
            /** Format: date-time */
            updated_at: string;
        };
        WSNoteUpdatedPayload: {
            /** Format: uuid */
            id: string;
            path: string;
            /** Format: date-time */
            updated_at: string;
        };
        WSNoteDeletedPayload: {
            /** Format: uuid */
            id: string;
            path: string;
        };
        WSNoteMovedPayload: {
            /** Format: uuid */
            id: string;
            old_path: string;
            new_path: string;
            /** Format: date-time */
            updated_at: string;
            title: string;
        };
        WSFolderCreatedPayload: {
            path: string;
            name: string;
        };
        WSFolderDeletedPayload: {
            path: string;
            recursive: boolean;
        };
        WSFolderMovedPayload: {
            old_path: string;
            new_path: string;
        };
        /** @description Empty payload — server-originated. */
        WSReindexStartedPayload: Record<string, never>;
        WSReindexCompletePayload: {
            notes_indexed: number;
        };
        /**
         * @description Returned by PUT /notes/{id} when If-Match does not match the
         *     current file's updated_at (SYNC-06). The client surfaces
         *     SYNC-05's Save-anyway / Discard banner using
         *     current_updated_at as the new comparator.
         */
        StaleWriteError: {
            /** @enum {string} */
            code: "stale_write";
            message: string;
            /** Format: date-time */
            current_updated_at: string;
        };
    };
    responses: never;
    parameters: {
        /** @description UUID of the note (Phase 1 has exactly one — see scratchpad UUID in code) */
        NoteId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getNotes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of note metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteList"];
                };
            };
        };
    };
    postNotes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNoteRequest"];
            };
        };
        responses: {
            /** @description Note created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteSummary"];
                };
            };
            /** @description Invalid request (missing fields, illegal title chars, parent traversal) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Case-insensitive collision (DATA-12) OR parent_path does not resolve to a folder */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getNoteById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the note (Phase 1 has exactly one — see scratchpad UUID in code) */
                id: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Note found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Note not found (unknown UUID) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    putNoteById: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Optimistic concurrency comparator (SYNC-06). When present,
                 *     the server compares this value against the file's current
                 *     updated_at (RFC3339Nano UTC). On mismatch the server
                 *     returns 409 with `code: stale_write` and
                 *     `current_updated_at` in the body — the client surfaces
                 *     SYNC-05's Save-anyway / Discard banner. Permissive when
                 *     absent (curl / automation friendly). Server treats the
                 *     value as an opaque string round-trip; max length 256 chars.
                 */
                "If-Match"?: string;
            };
            path: {
                /** @description UUID of the note (Phase 1 has exactly one — see scratchpad UUID in code) */
                id: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNoteRequest"];
            };
        };
        responses: {
            /** @description Note updated; atomic write committed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateNoteResponse"];
                };
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Note not found (unknown UUID) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Stale write (SYNC-06) — If-Match mismatch */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaleWriteError"];
                };
            };
            /** @description Write failure on disk (atomic-rename or fsync error) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteNoteById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the note (Phase 1 has exactly one — see scratchpad UUID in code) */
                id: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Note not found (unknown UUID) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Delete failed (FS / SQLite mismatch) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    postNoteMove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the note (Phase 1 has exactly one — see scratchpad UUID in code) */
                id: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveNoteRequest"];
            };
        };
        responses: {
            /** @description Move committed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteSummary"];
                };
            };
            /** @description Invalid request (empty new_path, illegal chars, ".." escape) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Note not found (unknown UUID) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Case-insensitive collision with an existing note (DATA-12) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Move failed (FS / SQLite mismatch) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full tree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tree"];
                };
            };
            /** @description Tree projection failed (FS walk / SQLite error) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    postFolders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFolderRequest"];
            };
        };
        responses: {
            /** @description Folder created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderNode"];
                };
            };
            /** @description Invalid request (empty name, illegal chars, parent traversal) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Case-insensitive collision OR parent_path does not resolve to a folder */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteFolder: {
        parameters: {
            query: {
                /** @description Canonical relative path under notes/ (NFC + lowercase per DATA-11) */
                path: string;
                /**
                 * @description When false (default), the server returns 409 folder_not_empty if the
                 *     folder has any children. The Phase 3 Delete-folder dialog (UI-SPEC
                 *     §Surface 4) always sets recursive=true after the user confirms the
                 *     content-count copy.
                 */
                recursive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request (missing path, ".." escape) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Folder not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Folder not empty (recursive=false and folder has children) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Delete failed (FS / SQLite mismatch) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    postFolderMove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveFolderRequest"];
            };
        };
        responses: {
            /** @description Move committed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderNode"];
                };
            };
            /** @description Invalid request (empty paths, illegal chars, ".." escape) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description old_path does not resolve to a folder */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Case-insensitive collision with an existing folder */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Move failed (FS / SQLite mismatch) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAdminStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current migration runner state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationStatus"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
        };
    };
    putConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Config"];
            };
        };
        responses: {
            /** @description Config saved; echoes the persisted document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
            /** @description Invalid request (malformed body, unknown field, out-of-range numeric) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Save failed (filesystem error) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getApiV1Ws: {
        parameters: {
            query?: {
                /**
                 * @description Per-tab UUID generated by the client (sessionStorage).
                 *     Server adopts this as the connection's session_id; the
                 *     handshake message echoes it for confirmation. Treated as
                 *     opaque; max length 128 chars enforced in middleware
                 *     (T-04-03).
                 */
                session_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching protocols (WebSocket upgrade) */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a WebSocket request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postAdminReindex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReindexRequest"];
            };
        };
        responses: {
            /** @description Re-index accepted; Phase 2 returns after completion */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexResponse"];
                };
            };
            /** @description A re-index is already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Database is in unrecoverable state (Path 3 fired) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
