// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

// Anything whose owner offers actions right now. Each mutation names a
// mutation on the owning subgraph that takes the item id as its only required
// argument.
type Actionable interface {
	IsActionable()
	GetActions() []Action
}

// Anything a reference can point at. The id is the universal ref:
// <ns>:<kind>/<native>.
type Item interface {
	IsItem()
	GetID() string
	GetKind() ItemKind
	GetStatus() ItemStatus
	// Current title; for a DELETED item, the last one known.
	GetTitle() string
	// Last modification; for a DELETED item, the deletion time.
	GetUpdatedAt() *time.Time
}

// Anything with a deep link into the owning UI or an external site.
type Linkable interface {
	IsLinkable()
	GetURL() *string
}

// Anything with a kind-specific state the shell colours through its per-kind
// table: running, merged, active.
type Stateful interface {
	IsStateful()
	GetState() *string
}

// Anything a time lane can place. A run has startsAt; an event has both.
type Timed interface {
	IsTimed()
	GetStartsAt() *time.Time
	GetEndsAt() *time.Time
}

type Action struct {
	ID       string     `json:"id"`
	Label    string     `json:"label"`
	Kind     ActionKind `json:"kind"`
	Mutation string     `json:"mutation"`
}

type Backlink struct {
	Source *Note `json:"source"`
	// The alias the first occurrence shows, or empty.
	Display string `json:"display"`
	Embed   bool   `json:"embed"`
}

type Blob struct {
	ID        string     `json:"id"`
	Kind      ItemKind   `json:"kind"`
	Status    ItemStatus `json:"status"`
	Title     string     `json:"title"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	Mime      *string    `json:"mime,omitempty"`
	Size      *int       `json:"size,omitempty"`
	// Live paths holding these bytes.
	Paths []string `json:"paths"`
	// For a DELETED blob whose bytes changed in place, the id that took over.
	ReplacedBy *string `json:"replacedBy,omitempty"`
}

func (Blob) IsItem()                    {}
func (this Blob) GetID() string         { return this.ID }
func (this Blob) GetKind() ItemKind     { return this.Kind }
func (this Blob) GetStatus() ItemStatus { return this.Status }

// Current title; for a DELETED item, the last one known.
func (this Blob) GetTitle() string { return this.Title }

// Last modification; for a DELETED item, the deletion time.
func (this Blob) GetUpdatedAt() *time.Time { return this.UpdatedAt }

func (Blob) IsEntity() {}

// A reference into another system, returned as written. Jasper can say who
// references it, not what it is.
type ForeignRef struct {
	ID        string     `json:"id"`
	Kind      ItemKind   `json:"kind"`
	Status    ItemStatus `json:"status"`
	Title     string     `json:"title"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	Namespace string     `json:"namespace"`
}

func (ForeignRef) IsItem()                    {}
func (this ForeignRef) GetID() string         { return this.ID }
func (this ForeignRef) GetKind() ItemKind     { return this.Kind }
func (this ForeignRef) GetStatus() ItemStatus { return this.Status }

// Current title; for a DELETED item, the last one known.
func (this ForeignRef) GetTitle() string { return this.Title }

// Last modification; for a DELETED item, the deletion time.
func (this ForeignRef) GetUpdatedAt() *time.Time { return this.UpdatedAt }

type ItemChange struct {
	// The universal ref of the item that changed.
	ID     string         `json:"id"`
	Change ItemChangeKind `json:"change"`
	At     time.Time      `json:"at"`
}

type Note struct {
	ID        string     `json:"id"`
	Kind      ItemKind   `json:"kind"`
	Status    ItemStatus `json:"status"`
	Title     string     `json:"title"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Vault-relative path; for a DELETED note, the last one.
	Path *string `json:"path,omitempty"`
	// The markdown as on disk. Null when the note is not OK.
	Body *string `json:"body,omitempty"`
	// The first stretch of body text, at most 200 characters.
	Excerpt *string `json:"excerpt,omitempty"`
	// Every target this note references, in universal form.
	Refs []string `json:"refs"`
	// Notes referencing this one, by title or by id.
	Backlinks []Backlink `json:"backlinks"`
}

func (Note) IsItem()                    {}
func (this Note) GetID() string         { return this.ID }
func (this Note) GetKind() ItemKind     { return this.Kind }
func (this Note) GetStatus() ItemStatus { return this.Status }

// Current title; for a DELETED item, the last one known.
func (this Note) GetTitle() string { return this.Title }

// Last modification; for a DELETED item, the deletion time.
func (this Note) GetUpdatedAt() *time.Time { return this.UpdatedAt }

func (Note) IsEntity() {}

type Query struct {
}

type Subscription struct {
}

type ActionKind string

const (
	ActionKindNavigate ActionKind = "NAVIGATE"
	ActionKindMutate   ActionKind = "MUTATE"
	ActionKindSpawn    ActionKind = "SPAWN"
)

var AllActionKind = []ActionKind{
	ActionKindNavigate,
	ActionKindMutate,
	ActionKindSpawn,
}

func (e ActionKind) IsValid() bool {
	switch e {
	case ActionKindNavigate, ActionKindMutate, ActionKindSpawn:
		return true
	}
	return false
}

func (e ActionKind) String() string {
	return string(e)
}

func (e *ActionKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActionKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActionKind", str)
	}
	return nil
}

func (e ActionKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActionKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActionKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ItemChangeKind string

const (
	ItemChangeKindCreated     ItemChangeKind = "CREATED"
	ItemChangeKindUpdated     ItemChangeKind = "UPDATED"
	ItemChangeKindDeleted     ItemChangeKind = "DELETED"
	ItemChangeKindMoved       ItemChangeKind = "MOVED"
	ItemChangeKindRefsChanged ItemChangeKind = "REFS_CHANGED"
)

var AllItemChangeKind = []ItemChangeKind{
	ItemChangeKindCreated,
	ItemChangeKindUpdated,
	ItemChangeKindDeleted,
	ItemChangeKindMoved,
	ItemChangeKindRefsChanged,
}

func (e ItemChangeKind) IsValid() bool {
	switch e {
	case ItemChangeKindCreated, ItemChangeKindUpdated, ItemChangeKindDeleted, ItemChangeKindMoved, ItemChangeKindRefsChanged:
		return true
	}
	return false
}

func (e ItemChangeKind) String() string {
	return string(e)
}

func (e *ItemChangeKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ItemChangeKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ItemChangeKind", str)
	}
	return nil
}

func (e ItemChangeKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ItemChangeKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ItemChangeKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Output-only, so the supergraph is the union of every subgraph's values.
// Each subgraph lists only the kinds it owns, plus FOREIGN for its stub.
type ItemKind string

const (
	ItemKindForeign ItemKind = "FOREIGN"
	ItemKindNote    ItemKind = "NOTE"
	ItemKindBlob    ItemKind = "BLOB"
)

var AllItemKind = []ItemKind{
	ItemKindForeign,
	ItemKindNote,
	ItemKindBlob,
}

func (e ItemKind) IsValid() bool {
	switch e {
	case ItemKindForeign, ItemKindNote, ItemKindBlob:
		return true
	}
	return false
}

func (e ItemKind) String() string {
	return string(e)
}

func (e *ItemKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ItemKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ItemKind", str)
	}
	return nil
}

func (e ItemKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ItemKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ItemKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ItemStatus string

const (
	ItemStatusOk      ItemStatus = "OK"
	ItemStatusUnknown ItemStatus = "UNKNOWN"
	ItemStatusDeleted ItemStatus = "DELETED"
)

var AllItemStatus = []ItemStatus{
	ItemStatusOk,
	ItemStatusUnknown,
	ItemStatusDeleted,
}

func (e ItemStatus) IsValid() bool {
	switch e {
	case ItemStatusOk, ItemStatusUnknown, ItemStatusDeleted:
		return true
	}
	return false
}

func (e ItemStatus) String() string {
	return string(e)
}

func (e *ItemStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ItemStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ItemStatus", str)
	}
	return nil
}

func (e ItemStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ItemStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ItemStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
