// Package wshub is the server-side WebSocket connection hub for
// multi-tab session sync.
//
// The hub is the third port the notes.Service consumes (alongside
// FileStore + Index). Service mutations call (*Hub).Broadcast AFTER a
// successful FS write + Index.Upsert (FS-FIRST / INDEX-SECOND /
// BROADCAST-THIRD). The hub fans out the resulting Envelope to all
// connected clients EXCEPT the one whose session_id matches the
// originating session.
//
// Wire format is locked to api/openapi.yaml's WSEnvelope schema; the
// event-type constants below mirror that enum 1:1.
//
// SECURITY: Broadcast payloads MUST NOT contain note content — only
// metadata (id, path, updated_at, title, etc.). Callers are expected
// to honor this by passing maps shaped per the WS*Payload schemas.
package wshub

import (
	"encoding/json"

	apigen "github.com/matthewoden/jasper/backend/internal/api"
)

// Compile-time bridge: this blank import ensures the compiler errors here
// if api.WSEnvelope is ever removed from the generated code. We cannot use
// a type alias because wshub.Envelope uses json.RawMessage for Payload
// (marshal-once) while apigen.WSEnvelope uses interface{}. The sentinel var
// catches schema removal; hub_test.go assertions catch field-level drift.
//
//nolint:unused // compile-time bridge sentinel (Amendment 2)
var _ apigen.WSEnvelope

// Envelope is the wire shape for every server-broadcast WS message.
// Payload is json.RawMessage so we marshal it ONCE at broadcast time
// and reuse the bytes for every recipient — do not marshal per-client.
//
// wshub.Envelope mirrors api.WSEnvelope (generated by oapi-codegen).
// The difference is Payload: json.RawMessage here vs interface{} in the
// generated type. Field names and JSON tags are identical. hub_test.go
// uses api.WSEnvelope literals for decoded-message assertions to prevent
// schema drift.
type Envelope struct {
	Event           string          `json:"event"`
	OriginSessionID string          `json:"origin_session_id"`
	Payload         json.RawMessage `json:"payload"`
}

// Event-type constants — locked to api/openapi.yaml's WSEnvelope.event
// enum. DO NOT add, remove, or rename without also editing the OpenAPI spec.
const (
	EventSessionAssigned = "session:assigned"
	EventNoteCreated     = "note:created"
	EventNoteUpdated     = "note:updated"
	EventNoteDeleted     = "note:deleted"
	EventNoteMoved       = "note:moved"
	EventFolderCreated   = "folder:created"
	EventFolderDeleted   = "folder:deleted"
	EventFolderMoved     = "folder:moved"
	EventFileCreated     = "file:created"
	EventFileDeleted     = "file:deleted"
	EventFileMoved       = "file:moved"
	EventTagsUpdated     = "tags:updated"
	EventReindexStarted  = "reindex:started"
	EventReindexComplete = "reindex:complete"
	EventMigrationStatus = "migration:status"

	// EventMcpGrantChanged is broadcast by the /mcp/grants CRUD handlers
	// whenever a grant is created, upgraded, or revoked. Callers MUST
	// broadcast with origin_session_id = "" so every connected tab
	// refreshes its MCP indicators (the per-session origin filter would
	// otherwise drop the event for the originating tab). Matches the
	// openapi.yaml WSEnvelope.event enum entry "mcp:grant_changed" —
	// drift here breaks the schema-typed fixture sentinel above.
	EventMcpGrantChanged = "mcp:grant_changed"

	// EventVaultSwitching is broadcast at the start of a hot-swap.
	// Payload: {"target_path": string, "target_display_name": string}.
	// The SPA mounts VaultSwitchOverlay on receipt.
	// Broadcast with origin_session_id = "" — all tabs must show the overlay.
	EventVaultSwitching = "vault.switching"

	// EventVaultSwitched is broadcast after the new vault's subsystems are
	// fully up. Payload: {"path": string, "display_name": string}. The SPA
	// calls window.location.reload() on receipt; a 10-second failsafe reload
	// is set on vault.switching so a lost vault.switched does not strand the SPA.
	// Broadcast with origin_session_id = "" — all tabs must reload.
	EventVaultSwitched = "vault.switched"
)
