// Package wshub is the server-side WebSocket connection hub for Phase 4
// multi-tab session sync.
//
// The hub is the third port the notes.Service consumes (alongside
// FileStore + Index). Service mutations call (*Hub).Broadcast AFTER a
// successful FS write + Index.Upsert (per ARCHITECTURE.md §11.1's
// FS-FIRST / INDEX-SECOND / BROADCAST-THIRD ordering). The hub fans
// out the resulting Envelope to all connected clients EXCEPT the one
// whose session_id matches the originating session.
//
// Wire format is locked to api/openapi.yaml's components.schemas.
// WSEnvelope; the event-type constants below mirror that enum 1:1.
//
// SECURITY (T-04-04): Broadcast payloads MUST NOT contain note content.
// Only metadata (id, path, updated_at, title, etc.) is permitted.
// Callers are expected to honor this by passing maps shaped per
// api/openapi.yaml's WS*Payload schemas.
package wshub

import (
	"encoding/json"

	apigen "github.com/matthewoden/jasper/backend/internal/api"
)

// Amendment 2 compile-time bridge: this blank import ensures the
// compiler errors here if api.WSEnvelope is ever removed from the
// generated code. We cannot use a type alias because wshub.Envelope
// uses json.RawMessage for Payload (marshal-once optimization) while
// apigen.WSEnvelope uses interface{}. The sentinel var below catches
// schema removal; hub_test.go assertions using apigen.WSEnvelope
// literals catch schema drift on individual fields.
//
//nolint:unused // compile-time bridge sentinel (Amendment 2)
var _ apigen.WSEnvelope

// Envelope is the wire shape for every server-broadcast WS message.
// Payload is json.RawMessage so we marshal it ONCE at broadcast time
// and reuse the bytes for every recipient (anti-pattern in
// RESEARCH.md §"Marshalling the Envelope per-client": don't marshal
// per-client).
//
// Amendment 2 (schema-typed fixtures): wshub.Envelope mirrors the wire
// shape of api.WSEnvelope (generated by oapi-codegen from Plan 04-01).
// The difference is Payload: we use json.RawMessage (marshal-once
// optimization) while the generated type uses interface{}. Field names
// and JSON tags are identical. hub_test.go uses api.WSEnvelope literals
// for decoded-message assertions to prevent schema drift.
type Envelope struct {
	Event           string          `json:"event"`
	OriginSessionID string          `json:"origin_session_id"`
	Payload         json.RawMessage `json:"payload"`
}

// Event-type constants — locked to api/openapi.yaml's
// components.schemas.WSEnvelope.event enum (Plan 04-01). DO NOT add,
// remove, or rename without also editing the OpenAPI spec.
const (
	EventSessionAssigned = "session:assigned"
	EventNoteCreated     = "note:created"
	EventNoteUpdated     = "note:updated"
	EventNoteDeleted     = "note:deleted"
	EventNoteMoved       = "note:moved"
	EventFolderCreated   = "folder:created"
	EventFolderDeleted   = "folder:deleted"
	EventFolderMoved     = "folder:moved"
	EventTagsUpdated     = "tags:updated"
	EventReindexStarted  = "reindex:started"
	EventReindexComplete = "reindex:complete"
	EventMigrationStatus = "migration:status"

	// EventMcpGrantChanged is broadcast by the /mcp/grants CRUD
	// handlers (Phase 8 Plan 08-08, D-57) whenever a grant is
	// created, upgraded, or revoked. Callers MUST broadcast with
	// origin_session_id = "" so every connected tab refreshes its
	// MCP indicators (the per-session origin filter in
	// frontend/src/lib/useSessionSync.ts:65 would otherwise drop the
	// event for the originating tab). Matches the openapi.yaml
	// WSEnvelope.event enum entry "mcp:grant_changed" — drift here
	// breaks the schema-typed fixture sentinel above.
	EventMcpGrantChanged = "mcp:grant_changed"

	// EventVaultSwitching is broadcast at the start of a hot-swap
	// (Plan 08-17d SwitchVault). Payload: {"target_path": string,
	// "target_display_name": string}. The SPA mounts VaultSwitchOverlay
	// on receipt. Broadcast with origin_session_id = "" — all tabs must
	// show the overlay.
	EventVaultSwitching = "vault.switching"

	// EventVaultSwitched is broadcast after the new vault's subsystems
	// are fully up (Plan 08-17d SwitchVault). Payload: {"path": string,
	// "display_name": string}. The SPA calls window.location.reload()
	// on receipt; a 10-second failsafe reload is set on vault.switching
	// (V4) so a lost vault.switched does not leave the SPA stranded.
	// Broadcast with origin_session_id = "" — all tabs must reload.
	EventVaultSwitched = "vault.switched"
)
