/**
 * The single network surface for note operations. Per CONTEXT.md API-03 / the
 * `<no_fetch_rule>` in 01-03-PLAN.md: the frontend NEVER hand-writes a request
 * shape — every API call routes through the typed openapi-fetch client.
 *
 * Components import these wrappers, not `client` directly, so the API surface
 * in this module is the only thing tests have to mock. A grep gate in the
 * plan's verification block enforces that no raw network call appears
 * anywhere in src/ outside test-setup.ts and node_modules.
 *
 * The path key `"/notes/{id}"` matches the OpenAPI schema generated by
 * openapi-typescript v7 from `api/openapi.yaml` — it is the typed key, not a
 * URL string. The actual URL is composed by openapi-fetch from the client's
 * baseUrl (`"/"` per Plan 01's client.ts) plus the spec's `servers` prefix
 * `/api/v1`, yielding `/api/v1/notes/{id}` over the wire.
 */

import { client } from "../api/client";

/**
 * Hard-coded UUID for the Phase 1 scratchpad note. Must match the backend's
 * notes.ScratchpadUUID constant byte-for-byte (CONTEXT.md D-06 / Plan 02).
 * Phase 3 introduces dynamic UUIDs without changing the URL shape.
 */
export const ScratchpadUUID =
  "00000000-0000-4000-a000-000000000001" as const;

export function getNote(id: string, options?: { signal?: AbortSignal }) {
  return client.GET("/notes/{id}", {
    params: { path: { id } },
    ...(options?.signal ? { signal: options.signal } : {}),
  });
}

export function updateNote(id: string, content: string, ifMatch?: string) {
  return client.PUT("/notes/{id}", {
    params: { path: { id } },
    body: { content },
    ...(ifMatch ? { headers: { "If-Match": ifMatch } } : {}),
  });
}

/**
 * NoteSearchResult — shape returned by GET /api/v1/notes/search-titles.
 * Matches the NoteSearchResult component schema in api/openapi.yaml (Plan 06-02).
 */
export interface NoteSearchResult {
  id: string;
  title: string;
  folder?: string | null;
  recency_score: number;
  proximity_score?: number | null;
}

/**
 * Search note titles for wiki-link autocomplete (LINKS-06 / D-13).
 * Empty q returns most-recently-edited notes up to limit.
 * Server ranks by recency (60%) + proximity (40%) per D-13.
 *
 * Throws on HTTP error so the caller can catch and degrade gracefully.
 */
export async function searchTitles(
  q: string,
  limit = 10,
): Promise<NoteSearchResult[]> {
  const { data, error } = await client.GET("/notes/search-titles", {
    params: { query: { q, limit } },
  });
  if (error) {
    throw new Error("searchTitles: " + JSON.stringify(error));
  }
  return data.results as NoteSearchResult[];
}

/**
 * createNoteFromMarkdownDrop — Plan 07-39 (UAT-5 N2-sub-A).
 *
 * Frontend-only routing decision: backend /files refuses .md uploads per the
 * security posture locked in Plan 07-34 (DATA-12 case-collision semantics live
 * in POST /notes, not POST /files). When the user drops a .md file into the
 * sidebar, FileTree.handleSidebarFileDrop detects the extension client-side
 * and calls this helper instead of filesApi.uploadFile.
 *
 * Two-step server flow:
 *   1. POST /notes {parent_path, title}  → creates an empty .md, returns id
 *   2. PUT  /notes/{id} {content: body}  → populates the body from the drop
 *
 * Why two steps: the existing POST /notes contract creates an empty file
 * (DESIGN.md §4) and we do not modify the wire shape. The PUT pairs with the
 * existing autosave flow so server-side state — including the SQLite FTS5
 * index — picks up the body content on the same single-flight refresh
 * cycle the rest of the tree already triggers.
 *
 * Errors:
 *   - 409 from POST: case-collision (DATA-12) OR parent_path doesn't resolve
 *     to a folder. Throws — caller surfaces toast; does NOT auto-rename.
 *   - 400 from POST: invalid title chars / traversal — throws.
 *   - PUT failure after successful POST: the empty .md remains; throws.
 *
 * @param notePath relative path including filename ("docs/foo.md" or "foo.md")
 * @param body markdown content to write to the new note
 */
export async function createNoteFromMarkdownDrop(
  notePath: string,
  body: string,
): Promise<{ id: string; path: string }> {
  const lastSlash = notePath.lastIndexOf("/");
  const parentPath = lastSlash === -1 ? "" : notePath.slice(0, lastSlash);
  const filename = lastSlash === -1 ? notePath : notePath.slice(lastSlash + 1);
  const title = filename.toLowerCase().endsWith(".md")
    ? filename.slice(0, -3)
    : filename;

  const { data, error, response } = await client.POST("/notes", {
    body: { parent_path: parentPath, title },
  });
  if (error || !data) {
    const status = response.status;
    const code =
      error && typeof error === "object" && "code" in error
        ? String((error as { code: unknown }).code)
        : "unknown";
    const message =
      error && typeof error === "object" && "message" in error
        ? String((error as { message: unknown }).message)
        : "createNote failed";
    const err = new Error(
      `createNoteFromMarkdownDrop: POST /notes failed (${status} ${code}): ${message}`,
    ) as Error & { status?: number; code?: string };
    err.status = status;
    err.code = code;
    throw err;
  }

  const note = data;

  if (body.length > 0) {
    const { error: putErr, response: putResp } = await client.PUT("/notes/{id}", {
      params: { path: { id: note.id } },
      body: { content: body },
    });
    if (putErr) {
      const status = putResp.status;
      const err = new Error(
        `createNoteFromMarkdownDrop: PUT /notes/${note.id} failed (${status}); empty note left at ${note.path}`,
      ) as Error & { status?: number };
      err.status = status;
      throw err;
    }
  }

  return { id: note.id, path: note.path };
}
