/**
 * The single network surface for note operations. Per CONTEXT.md API-03 / the
 * `<no_fetch_rule>` in 01-03-PLAN.md: the frontend NEVER hand-writes a request
 * shape — every API call routes through the typed openapi-fetch client.
 *
 * Components import these wrappers, not `client` directly, so the API surface
 * in this module is the only thing tests have to mock. A grep gate in the
 * plan's verification block enforces that no raw network call appears
 * anywhere in src/ outside test-setup.ts and node_modules.
 *
 * The path key `"/notes/{id}"` matches the OpenAPI schema generated by
 * openapi-typescript v7 from `api/openapi.yaml` — it is the typed key, not a
 * URL string. The actual URL is composed by openapi-fetch from the client's
 * baseUrl (`"/"` per Plan 01's client.ts) plus the spec's `servers` prefix
 * `/api/v1`, yielding `/api/v1/notes/{id}` over the wire.
 */

import { client } from "../api/client";

/**
 * Hard-coded UUID for the Phase 1 scratchpad note. Must match the backend's
 * notes.ScratchpadUUID constant byte-for-byte (CONTEXT.md D-06 / Plan 02).
 * Phase 3 introduces dynamic UUIDs without changing the URL shape.
 */
export const ScratchpadUUID =
  "00000000-0000-4000-a000-000000000001" as const;

export function getNote(id: string) {
  return client.GET("/notes/{id}", {
    params: { path: { id } },
  });
}

export function updateNote(id: string, content: string, ifMatch?: string) {
  return client.PUT("/notes/{id}", {
    params: { path: { id } },
    body: { content },
    ...(ifMatch ? { headers: { "If-Match": ifMatch } } : {}),
  });
}
